"""Static validated material data; see docs/material-catalog.md for provenance.

Checked 2026-09-08. Capacities are explicit data, including source exceptions.
Columns: symbol, English name, category, grade, maximum, group, subgroup, i18n key.
"""

MATERIALS = (
    ('antimony', 'Antimony', 'Raw', 4, 150, 'standard', 'raw_7', 'body_detail.material.antimony'),
    ('arsenic', 'Arsenic', 'Raw', 2, 250, 'standard', 'raw_6', 'body_detail.material.arsenic'),
    ('boron', 'Boron', 'Raw', 3, 200, 'standard', 'raw_7', 'body_detail.material.boron'),
    ('cadmium', 'Cadmium', 'Raw', 3, 200, 'standard', 'raw_3', 'body_detail.material.cadmium'),
    ('carbon', 'Carbon', 'Raw', 1, 300, 'standard', 'raw_1', 'body_detail.material.carbon'),
    ('chromium', 'Chromium', 'Raw', 2, 250, 'standard', 'raw_2', 'body_detail.material.chromium'),
    ('germanium', 'Germanium', 'Raw', 2, 250, 'standard', 'raw_5', 'body_detail.material.germanium'),
    ('iron', 'Iron', 'Raw', 1, 300, 'standard', 'raw_4', 'body_detail.material.iron'),
    ('lead', 'Lead', 'Raw', 1, 300, 'standard', 'raw_7', 'body_detail.material.lead'),
    ('manganese', 'Manganese', 'Raw', 2, 250, 'standard', 'raw_3', 'body_detail.material.manganese'),
    ('mercury', 'Mercury', 'Raw', 3, 200, 'standard', 'raw_6', 'body_detail.material.mercury'),
    ('molybdenum', 'Molybdenum', 'Raw', 3, 200, 'standard', 'raw_2', 'body_detail.material.molybdenum'),
    ('nickel', 'Nickel', 'Raw', 1, 300, 'standard', 'raw_5', 'body_detail.material.nickel'),
    ('niobium', 'Niobium', 'Raw', 3, 200, 'standard', 'raw_1', 'body_detail.material.niobium'),
    ('phosphorus', 'Phosphorus', 'Raw', 1, 300, 'standard', 'raw_2', 'body_detail.material.phosphorus'),
    ('polonium', 'Polonium', 'Raw', 4, 150, 'standard', 'raw_6', 'body_detail.material.polonium'),
    ('rhenium', 'Rhenium', 'Raw', 1, 300, 'standard', 'raw_6', 'body_detail.material.rhenium'),
    ('ruthenium', 'Ruthenium', 'Raw', 4, 150, 'standard', 'raw_3', 'body_detail.material.ruthenium'),
    ('selenium', 'Selenium', 'Raw', 4, 150, 'standard', 'raw_4', 'body_detail.material.selenium'),
    ('sulphur', 'Sulphur', 'Raw', 1, 300, 'standard', 'raw_3', 'body_detail.material.sulphur'),
    ('technetium', 'Technetium', 'Raw', 4, 150, 'standard', 'raw_2', 'body_detail.material.technetium'),
    ('tellurium', 'Tellurium', 'Raw', 4, 150, 'standard', 'raw_5', 'body_detail.material.tellurium'),
    ('tin', 'Tin', 'Raw', 3, 200, 'standard', 'raw_4', 'body_detail.material.tin'),
    ('tungsten', 'Tungsten', 'Raw', 3, 200, 'standard', 'raw_5', 'body_detail.material.tungsten'),
    ('vanadium', 'Vanadium', 'Raw', 2, 250, 'standard', 'raw_1', 'body_detail.material.vanadium'),
    ('yttrium', 'Yttrium', 'Raw', 4, 150, 'standard', 'raw_1', 'body_detail.material.yttrium'),
    ('zinc', 'Zinc', 'Raw', 2, 250, 'standard', 'raw_4', 'body_detail.material.zinc'),
    ('zirconium', 'Zirconium', 'Raw', 2, 250, 'standard', 'raw_7', 'body_detail.material.zirconium'),
    ('basicconductors', 'Basic Conductors', 'Manufactured', 1, 300, 'standard', 'conductive', 'body_detail.material.basicconductors'),
    ('biotechconductors', 'Biotech Conductors', 'Manufactured', 5, 100, 'standard', 'conductive', 'body_detail.material.biotechconductors'),
    ('chemicaldistillery', 'Chemical Distillery', 'Manufactured', 3, 200, 'standard', 'chemical', 'body_detail.material.chemicaldistillery'),
    ('chemicalmanipulators', 'Chemical Manipulators', 'Manufactured', 4, 150, 'standard', 'chemical', 'body_detail.material.chemicalmanipulators'),
    ('chemicalprocessors', 'Chemical Processors', 'Manufactured', 2, 250, 'standard', 'chemical', 'body_detail.material.chemicalprocessors'),
    ('chemicalstorageunits', 'Chemical Storage Units', 'Manufactured', 1, 300, 'standard', 'chemical', 'body_detail.material.chemicalstorageunits'),
    ('compactcomposites', 'Compact Composites', 'Manufactured', 1, 300, 'standard', 'composite', 'body_detail.material.compactcomposites'),
    ('compoundshielding', 'Compound Shielding', 'Manufactured', 4, 150, 'standard', 'shielding', 'body_detail.material.compoundshielding'),
    ('conductiveceramics', 'Conductive Ceramics', 'Manufactured', 3, 200, 'standard', 'conductive', 'body_detail.material.conductiveceramics'),
    ('conductivecomponents', 'Conductive Components', 'Manufactured', 2, 250, 'standard', 'conductive', 'body_detail.material.conductivecomponents'),
    ('conductivepolymers', 'Conductive Polymers', 'Manufactured', 4, 150, 'standard', 'conductive', 'body_detail.material.conductivepolymers'),
    ('configurablecomponents', 'Configurable Components', 'Manufactured', 4, 150, 'standard', 'mechanical_components', 'body_detail.material.configurablecomponents'),
    ('crystalshards', 'Crystal Shards', 'Manufactured', 1, 300, 'standard', 'crystals', 'body_detail.material.crystalshards'),
    ('electrochemicalarrays', 'Electrochemical Arrays', 'Manufactured', 3, 200, 'standard', 'capacitors', 'body_detail.material.electrochemicalarrays'),
    ('exquisitefocuscrystals', 'Exquisite Focus Crystals', 'Manufactured', 5, 100, 'standard', 'crystals', 'body_detail.material.exquisitefocuscrystals'),
    ('fedcorecomposites', 'Core Dynamics Composites', 'Manufactured', 5, 100, 'standard', 'composite', 'body_detail.material.fedcorecomposites'),
    ('fedproprietarycomposites', 'Proprietary Composites', 'Manufactured', 4, 150, 'standard', 'composite', 'body_detail.material.fedproprietarycomposites'),
    ('filamentcomposites', 'Filament Composites', 'Manufactured', 2, 250, 'standard', 'composite', 'body_detail.material.filamentcomposites'),
    ('focuscrystals', 'Focus Crystals', 'Manufactured', 3, 200, 'standard', 'crystals', 'body_detail.material.focuscrystals'),
    ('galvanisingalloys', 'Galvanising Alloys', 'Manufactured', 2, 250, 'standard', 'alloys', 'body_detail.material.galvanisingalloys'),
    ('gridresistors', 'Grid Resistors', 'Manufactured', 1, 300, 'standard', 'capacitors', 'body_detail.material.gridresistors'),
    ('guardian_powercell', 'Guardian Power Cell', 'Manufactured', 1, 300, 'guardian', None, 'body_detail.material.guardian_powercell'),
    ('guardian_powerconduit', 'Guardian Power Conduit', 'Manufactured', 2, 250, 'guardian', None, 'body_detail.material.guardian_powerconduit'),
    ('guardian_sentinel_weaponparts', 'Guardian Sentinel Weapon Parts', 'Manufactured', 3, 200, 'guardian', None, 'body_detail.material.guardian_sentinel_weaponparts'),
    ('guardian_sentinel_wreckagecomponents', 'Guardian Sentinel Wreckage Components', 'Manufactured', 1, 300, 'guardian', None, 'body_detail.material.guardian_sentinel_wreckagecomponents'),
    ('guardian_techcomponent', 'Guardian Technology Component', 'Manufactured', 3, 200, 'guardian', None, 'body_detail.material.guardian_techcomponent'),
    ('heatconductionwiring', 'Heat Conduction Wiring', 'Manufactured', 1, 300, 'standard', 'heat', 'body_detail.material.heatconductionwiring'),
    ('heatdispersionplate', 'Heat Dispersion Plate', 'Manufactured', 2, 250, 'standard', 'heat', 'body_detail.material.heatdispersionplate'),
    ('heatexchangers', 'Heat Exchangers', 'Manufactured', 3, 200, 'standard', 'heat', 'body_detail.material.heatexchangers'),
    ('heatresistantceramics', 'Heat Resistant Ceramics', 'Manufactured', 2, 250, 'standard', 'thermic', 'body_detail.material.heatresistantceramics'),
    ('heatvanes', 'Heat Vanes', 'Manufactured', 4, 150, 'standard', 'heat', 'body_detail.material.heatvanes'),
    ('highdensitycomposites', 'High Density Composites', 'Manufactured', 3, 200, 'standard', 'composite', 'body_detail.material.highdensitycomposites'),
    ('hybridcapacitors', 'Hybrid Capacitors', 'Manufactured', 2, 250, 'standard', 'capacitors', 'body_detail.material.hybridcapacitors'),
    ('imperialshielding', 'Imperial Shielding', 'Manufactured', 5, 100, 'standard', 'shielding', 'body_detail.material.imperialshielding'),
    ('improvisedcomponents', 'Improvised Components', 'Manufactured', 5, 100, 'standard', 'mechanical_components', 'body_detail.material.improvisedcomponents'),
    ('mechanicalcomponents', 'Mechanical Components', 'Manufactured', 3, 200, 'standard', 'mechanical_components', 'body_detail.material.mechanicalcomponents'),
    ('mechanicalequipment', 'Mechanical Equipment', 'Manufactured', 2, 250, 'standard', 'mechanical_components', 'body_detail.material.mechanicalequipment'),
    ('mechanicalscrap', 'Mechanical Scrap', 'Manufactured', 1, 300, 'standard', 'mechanical_components', 'body_detail.material.mechanicalscrap'),
    ('militarygradealloys', 'Military Grade Alloys', 'Manufactured', 5, 100, 'standard', 'thermic', 'body_detail.material.militarygradealloys'),
    ('militarysupercapacitors', 'Military Supercapacitors', 'Manufactured', 5, 100, 'standard', 'capacitors', 'body_detail.material.militarysupercapacitors'),
    ('pharmaceuticalisolators', 'Pharmaceutical Isolators', 'Manufactured', 5, 100, 'standard', 'chemical', 'body_detail.material.pharmaceuticalisolators'),
    ('phasealloys', 'Phase Alloys', 'Manufactured', 3, 200, 'standard', 'alloys', 'body_detail.material.phasealloys'),
    ('polymercapacitors', 'Polymer Capacitors', 'Manufactured', 4, 150, 'standard', 'capacitors', 'body_detail.material.polymercapacitors'),
    ('precipitatedalloys', 'Precipitated Alloys', 'Manufactured', 3, 200, 'standard', 'thermic', 'body_detail.material.precipitatedalloys'),
    ('protoheatradiators', 'Proto Heat Radiators', 'Manufactured', 5, 100, 'standard', 'heat', 'body_detail.material.protoheatradiators'),
    ('protolightalloys', 'Proto Light Alloys', 'Manufactured', 4, 150, 'standard', 'alloys', 'body_detail.material.protolightalloys'),
    ('protoradiolicalloys', 'Proto Radiolic Alloys', 'Manufactured', 5, 100, 'standard', 'alloys', 'body_detail.material.protoradiolicalloys'),
    ('refinedfocuscrystals', 'Refined Focus Crystals', 'Manufactured', 4, 150, 'standard', 'crystals', 'body_detail.material.refinedfocuscrystals'),
    ('salvagedalloys', 'Salvaged Alloys', 'Manufactured', 1, 300, 'standard', 'alloys', 'body_detail.material.salvagedalloys'),
    ('shieldemitters', 'Shield Emitters', 'Manufactured', 2, 250, 'standard', 'shielding', 'body_detail.material.shieldemitters'),
    ('shieldingsensors', 'Shielding Sensors', 'Manufactured', 3, 200, 'standard', 'shielding', 'body_detail.material.shieldingsensors'),
    ('temperedalloys', 'Tempered Alloys', 'Manufactured', 1, 300, 'standard', 'thermic', 'body_detail.material.temperedalloys'),
    ('tg_abrasion01', 'Heat Exposure Specimen', 'Manufactured', 5, 100, 'thargoid', None, 'body_detail.material.tg_abrasion01'),
    ('tg_abrasion02', 'Phasing Membrane Residue', 'Manufactured', 3, 200, 'thargoid', None, 'body_detail.material.tg_abrasion02'),
    ('tg_abrasion03', 'Hardened Surface Fragments', 'Manufactured', 1, 300, 'thargoid', None, 'body_detail.material.tg_abrasion03'),
    ('tg_biomechanicalconduits', 'Thargoid Bio-Mechanical Conduits', 'Manufactured', 3, 200, 'thargoid', None, 'body_detail.material.tg_biomechanicalconduits'),
    ('tg_causticcrystal', 'Caustic Crystal', 'Manufactured', 4, 150, 'thargoid', None, 'body_detail.material.tg_causticcrystal'),
    ('tg_causticgeneratorparts', 'Corrosive Mechanisms', 'Manufactured', 3, 200, 'thargoid', None, 'body_detail.material.tg_causticgeneratorparts'),
    ('tg_causticshard', 'Caustic Shard', 'Manufactured', 2, 250, 'thargoid', None, 'body_detail.material.tg_causticshard'),
    ('tg_propulsionelement', 'Thargoid Propulsion Element', 'Manufactured', 5, 100, 'thargoid', None, 'body_detail.material.tg_propulsionelement'),
    ('tg_weaponparts', 'Thargoid Weapon Parts', 'Manufactured', 4, 150, 'thargoid', None, 'body_detail.material.tg_weaponparts'),
    ('tg_wreckagecomponents', 'Thargoid Wreckage Components', 'Manufactured', 3, 200, 'thargoid', None, 'body_detail.material.tg_wreckagecomponents'),
    ('thermicalloys', 'Thermic Alloys', 'Manufactured', 4, 150, 'standard', 'thermic', 'body_detail.material.thermicalloys'),
    ('uncutfocuscrystals', 'Flawed Focus Crystals', 'Manufactured', 2, 250, 'standard', 'crystals', 'body_detail.material.uncutfocuscrystals'),
    ('unknowncarapace', 'Thargoid Carapace', 'Manufactured', 2, 250, 'thargoid', None, 'body_detail.material.unknowncarapace'),
    ('unknowncorechip', 'Tactical Core Chip', 'Manufactured', 2, 100, 'thargoid', None, 'body_detail.material.unknowncorechip'),
    ('unknownenergycell', 'Thargoid Energy Cell', 'Manufactured', 3, 200, 'thargoid', None, 'body_detail.material.unknownenergycell'),
    ('unknownenergysource', 'Sensor Fragment', 'Manufactured', 5, 100, 'thargoid', None, 'body_detail.material.unknownenergysource'),
    ('unknownorganiccircuitry', 'Thargoid Organic Circuitry', 'Manufactured', 5, 100, 'thargoid', None, 'body_detail.material.unknownorganiccircuitry'),
    ('unknowntechnologycomponents', 'Thargoid Technology Components', 'Manufactured', 4, 150, 'thargoid', None, 'body_detail.material.unknowntechnologycomponents'),
    ('wornshieldemitters', 'Worn Shield Emitters', 'Manufactured', 1, 300, 'standard', 'shielding', 'body_detail.material.wornshieldemitters'),
    ('adaptiveencryptors', 'Adaptive Encryptors Capture', 'Encoded', 5, 100, 'standard', 'encryption_files', 'body_detail.material.adaptiveencryptors'),
    ('ancientbiologicaldata', 'Pattern Alpha Obelisk Data (Biological)', 'Encoded', 3, 150, 'guardian', None, 'body_detail.material.ancientbiologicaldata'),
    ('ancientculturaldata', 'Pattern Beta Obelisk Data (Cultural)', 'Encoded', 2, 150, 'guardian', None, 'body_detail.material.ancientculturaldata'),
    ('ancienthistoricaldata', 'Pattern Gamma Obelisk Data (Historical)', 'Encoded', 1, 150, 'guardian', None, 'body_detail.material.ancienthistoricaldata'),
    ('ancientlanguagedata', 'Pattern Delta Obelisk Data (Linguistic)', 'Encoded', 4, 150, 'guardian', None, 'body_detail.material.ancientlanguagedata'),
    ('ancienttechnologicaldata', 'Pattern Epsilon Obelisk Data (Technological)', 'Encoded', 4, 150, 'guardian', None, 'body_detail.material.ancienttechnologicaldata'),
    ('archivedemissiondata', 'Irregular Emission Data', 'Encoded', 2, 250, 'standard', 'emission_data', 'body_detail.material.archivedemissiondata'),
    ('bulkscandata', 'Anomalous Bulk Scan Data', 'Encoded', 1, 300, 'standard', 'data_archives', 'body_detail.material.bulkscandata'),
    ('classifiedscandata', 'Classified Scan Fragment', 'Encoded', 5, 100, 'standard', 'data_archives', 'body_detail.material.classifiedscandata'),
    ('compactemissionsdata', 'Abnormal Compact Emission Data', 'Encoded', 5, 100, 'standard', 'emission_data', 'body_detail.material.compactemissionsdata'),
    ('consumerfirmware', 'Modified Consumer Firmware', 'Encoded', 2, 250, 'standard', 'encoded_firmware', 'body_detail.material.consumerfirmware'),
    ('dataminedwake', 'Datamined Wake Exceptions', 'Encoded', 5, 100, 'standard', 'wake_scans', 'body_detail.material.dataminedwake'),
    ('decodedemissiondata', 'Decoded Emission Data', 'Encoded', 4, 150, 'standard', 'emission_data', 'body_detail.material.decodedemissiondata'),
    ('disruptedwakeechoes', 'Atypical Disrupted Wake Echoes', 'Encoded', 1, 300, 'standard', 'wake_scans', 'body_detail.material.disruptedwakeechoes'),
    ('embeddedfirmware', 'Modified Embedded Firmware', 'Encoded', 5, 100, 'standard', 'encoded_firmware', 'body_detail.material.embeddedfirmware'),
    ('emissiondata', 'Unexpected Emission Data', 'Encoded', 3, 200, 'standard', 'emission_data', 'body_detail.material.emissiondata'),
    ('encodedscandata', 'Divergent Scan Data', 'Encoded', 4, 150, 'standard', 'data_archives', 'body_detail.material.encodedscandata'),
    ('encryptedfiles', 'Unusual Encrypted Files', 'Encoded', 1, 300, 'standard', 'encryption_files', 'body_detail.material.encryptedfiles'),
    ('encryptionarchives', 'Atypical Encryption Archives', 'Encoded', 4, 150, 'standard', 'encryption_files', 'body_detail.material.encryptionarchives'),
    ('encryptioncodes', 'Tagged Encryption Codes', 'Encoded', 2, 250, 'standard', 'encryption_files', 'body_detail.material.encryptioncodes'),
    ('fsdtelemetry', 'Anomalous FSD Telemetry', 'Encoded', 2, 250, 'standard', 'wake_scans', 'body_detail.material.fsdtelemetry'),
    ('guardian_moduleblueprint', 'Guardian Module Blueprint', 'Encoded', 5, 150, 'guardian', None, 'body_detail.material.guardian_moduleblueprint'),
    ('guardian_vesselblueprint', 'Guardian Vessel Blueprint', 'Encoded', 5, 100, 'guardian', None, 'body_detail.material.guardian_vesselblueprint'),
    ('guardian_weaponblueprint', 'Guardian Weapon Blueprint', 'Encoded', 5, 150, 'guardian', None, 'body_detail.material.guardian_weaponblueprint'),
    ('hyperspacetrajectories', 'Eccentric Hyperspace Trajectories', 'Encoded', 4, 150, 'standard', 'wake_scans', 'body_detail.material.hyperspacetrajectories'),
    ('industrialfirmware', 'Cracked Industrial Firmware', 'Encoded', 3, 200, 'standard', 'encoded_firmware', 'body_detail.material.industrialfirmware'),
    ('legacyfirmware', 'Specialised Legacy Firmware', 'Encoded', 1, 300, 'standard', 'encoded_firmware', 'body_detail.material.legacyfirmware'),
    ('scanarchives', 'Unidentified Scan Archives', 'Encoded', 2, 250, 'standard', 'data_archives', 'body_detail.material.scanarchives'),
    ('scandatabanks', 'Classified Scan Databanks', 'Encoded', 3, 200, 'standard', 'data_archives', 'body_detail.material.scandatabanks'),
    ('scrambledemissiondata', 'Exceptional Scrambled Emission Data', 'Encoded', 1, 300, 'standard', 'emission_data', 'body_detail.material.scrambledemissiondata'),
    ('securityfirmware', 'Security Firmware Patch', 'Encoded', 4, 150, 'standard', 'encoded_firmware', 'body_detail.material.securityfirmware'),
    ('shieldcyclerecordings', 'Distorted Shield Cycle Recordings', 'Encoded', 1, 300, 'standard', 'shield_data', 'body_detail.material.shieldcyclerecordings'),
    ('shielddensityreports', 'Untypical Shield Scans', 'Encoded', 3, 200, 'standard', 'shield_data', 'body_detail.material.shielddensityreports'),
    ('shieldfrequencydata', 'Peculiar Shield Frequency Data', 'Encoded', 5, 100, 'standard', 'shield_data', 'body_detail.material.shieldfrequencydata'),
    ('shieldpatternanalysis', 'Aberrant Shield Pattern Analysis', 'Encoded', 4, 150, 'standard', 'shield_data', 'body_detail.material.shieldpatternanalysis'),
    ('shieldsoakanalysis', 'Inconsistent Shield Soak Analysis', 'Encoded', 2, 250, 'standard', 'shield_data', 'body_detail.material.shieldsoakanalysis'),
    ('symmetrickeys', 'Open Symmetric Keys', 'Encoded', 3, 200, 'standard', 'encryption_files', 'body_detail.material.symmetrickeys'),
    ('tg_compositiondata', 'Thargoid Material Composition Data', 'Encoded', 3, 200, 'thargoid', None, 'body_detail.material.tg_compositiondata'),
    ('tg_interdictiondata', 'Thargoid Interdiction Telemetry', 'Encoded', 3, 200, 'thargoid', None, 'body_detail.material.tg_interdictiondata'),
    ('tg_residuedata', 'Thargoid Residue Data', 'Encoded', 4, 150, 'thargoid', None, 'body_detail.material.tg_residuedata'),
    ('tg_shipflightdata', 'Ship Flight Data', 'Encoded', 3, 200, 'thargoid', None, 'body_detail.material.tg_shipflightdata'),
    ('tg_shipsystemsdata', 'Ship Systems Data', 'Encoded', None, None, 'thargoid', None, 'body_detail.material.tg_shipsystemsdata'),
    ('tg_shutdowndata', 'Massive Energy Surge Analytics', 'Encoded', 3, 200, 'thargoid', None, 'body_detail.material.tg_shutdowndata'),
    ('tg_structuraldata', 'Thargoid Structural Data', 'Encoded', 2, 250, 'thargoid', None, 'body_detail.material.tg_structuraldata'),
    ('unknownshipsignature', 'Thargoid Ship Signature', 'Encoded', 3, 200, 'thargoid', None, 'body_detail.material.unknownshipsignature'),
    ('unknownwakedata', 'Thargoid Wake Data', 'Encoded', 4, 150, 'thargoid', None, 'body_detail.material.unknownwakedata'),
    ('wakesolutions', 'Strange Wake Solutions', 'Encoded', 3, 200, 'standard', 'wake_scans', 'body_detail.material.wakesolutions'),
)

LEGACY_I18N_KEYS = frozenset((
    'body_detail.material.antimony',
    'body_detail.material.arsenic',
    'body_detail.material.cadmium',
    'body_detail.material.carbon',
    'body_detail.material.chromium',
    'body_detail.material.germanium',
    'body_detail.material.iron',
    'body_detail.material.manganese',
    'body_detail.material.mercury',
    'body_detail.material.molybdenum',
    'body_detail.material.nickel',
    'body_detail.material.niobium',
    'body_detail.material.phosphorus',
    'body_detail.material.polonium',
    'body_detail.material.ruthenium',
    'body_detail.material.selenium',
    'body_detail.material.sulphur',
    'body_detail.material.technetium',
    'body_detail.material.tellurium',
    'body_detail.material.tin',
    'body_detail.material.tungsten',
    'body_detail.material.vanadium',
    'body_detail.material.yttrium',
    'body_detail.material.zirconium',
))
