"""English content for contextual help."""


HELP_TOPICS = {'overview': ('Overview',
              '<h2>Overview</h2>\n'
              '<p>The overview is the home page of CMDRHelper. It summarizes the most important '
              'information about the currently active commander and shows at a glance whether the '
              'journal, location and online services are correctly recognized.</p>\n'
              '\n'
              '<h3>Commander & ship</h3>\n'
              '<p>The commander recognized from the Elite Dangerous Journal and the ship currently '
              'in use are displayed here.</p>\n'
              '<p>CMDRHelper assigns personal data to the respective commander based on the '
              'Frontier ID (FID). This keeps data from different commanders separate from each '
              'other.</p>\n'
              '<p>When changing the commander, the saved information associated with the new '
              'commander is loaded.</p>\n'
              '\n'
              '<h3>journal</h3>\n'
              "<p>CMDRHelper uses Elite Dangerous's journal files as its main data source.</p>\n"
              '<p>The journal display informs whether journal files have been found and assigned '
              'to the active commander. New complete journal entries are automatically processed '
              'during gameplay.</p>\n'
              '<p>Journal areas that have already been processed are saved so that CMDRHelper does '
              'not have to fully evaluate each journal again the next time it is started.</p>\n'
              '\n'
              '<h3>Current location</h3>\n'
              '<p>Shows the currently known star system and - as far as known from the journal - '
              'the exact location of the commander.</p>\n'
              '<p>The location is updated by events such as jumps, docking and other position '
              'reports and stored on a commander-by-command basis.</p>\n'
              '\n'
              '<h3>Missions</h3>\n'
              '<p>This area shows the number of currently known open missions.</p>\n'
              '<p>The “Missions” button or menu item takes you to the full mission view with the '
              'known mission objectives and status information.</p>\n'
              '\n'
              '<h3>Last Stand</h3>\n'
              '<p>“Last state” summarizes the last known persistent commander state. This allows '
              'important information to be restored even after restarting Elite Dangerous or '
              'CMDRHelper.</p>\n'
              '\n'
              '<h3>Final systems</h3>\n'
              '<p>Systems recently visited or recognized from the journal are displayed here.</p>\n'
              "<p>The list serves as a quick overview of the Commander's recent journey.</p>\n"
              '\n'
              '<h3>Online status</h3>\n'
              '<p>There are additional status indicators at the top of the main window:</p>\n'
              '<ul>\n'
              '<li><b>Journal recognized</b>– CMDRHelper detected a valid journal source and '
              'commander identity.</li>\n'
              '<li><b>EDSM</b>– shows the current status of the EDSM transmission for the active '
              'journal FID.</li>\n'
              '<li><b>INARA</b>– shows the current status of the Inara transmission for the active '
              'journal FID.</li>\n'
              '</ul>\n'
              '<p>Online access data is managed separately for each commander. A commander never '
              "automatically uses another commander's API-Key.</p>\n"
              '\n'
              '<h3>Important for multiple commanders</h3>\n'
              '<p>The live data always depends on the commander who was clearly identified by the '
              'current Elite Dangerous journal session.</p>\n'
              '<p>Merely displaying a different commander in a view does not change the active '
              'live commander or affect any EDSM or Inara broadcast.</p>\n'
              '\n'
              '<h3>Tip</h3>\n'
              '<p>If the commander, ship or location does not match the current state of the game, '
              'first check the journal display at the top and then check the journal folder set '
              'under “Settings”.</p>'),
 'missions': ('Missions',
              '<h2>Missions</h2>\n'
              '<p>The mission view shows the missions of the currently viewed commander known from '
              'the Elite Dangerous Journal. CMDRHelper saves mission data on a '
              'commander-by-command basis so that open missions are retained even after a restart '
              'of Elite Dangerous or CMDRHelper.</p>\n'
              '\n'
              '<h3>Open missions</h3>\n'
              '<p>New missions are coming out<code>MissionAccepted</code>taken over and saved '
              'permanently.</p>\n'
              '<p>As long as there is no final mission event, the mission remains open. A new game '
              'session without a mission list may not automatically remove known open '
              'missions.</p>\n'
              '\n'
              '<h3>Mission status</h3>\n'
              '<p>CMDRHelper processes, among others, the following status changes:</p>\n'
              '<ul>\n'
              '<li>Mission accepted</li>\n'
              '<li>Mission completed</li>\n'
              '<li>Mission failed</li>\n'
              '<li>Mission aborted</li>\n'
              '<li>Mission objective diverted</li>\n'
              '<li>Progress on supported cargo/depot missions</li>\n'
              '</ul>\n'
              '<p>A final event only changes the associated mission.</p>\n'
              '\n'
              '<h3>Missions from the Journal</h3>\n'
              '<p>Elite Dangerous provides mission information about various journal events. '
              'CMDRHelper merges these events into a persistent mission state.</p>\n'
              '<p>A real full mission event can serve as an authoritative snapshot. If such an '
              'event is missing, older open missions will not be closed for this reason '
              'alone.</p>\n'
              '\n'
              '<h3>Destinations and places</h3>\n'
              '<p>To the extent that Elite provides the information in the journal, CMDRHelper '
              'shows:</p>\n'
              '<ul>\n'
              '<li>Target system</li>\n'
              '<li>Destination station or destination</li>\n'
              '<li>Target planet or body</li>\n'
              '<li>Mission designation</li>\n'
              '<li>known progress</li>\n'
              '<li>current status</li>\n'
              '</ul>\n'
              '<p>Not every mission provides all the information. Missing data is not invented by '
              'CMDRHelper.</p>\n'
              '\n'
              '<h3>Persistence and restart</h3>\n'
              '<p>Open missions are saved in the commander-related database.</p>\n'
              '<p>This means they are retained even if:</p>\n'
              '<ul>\n'
              '<li>Elite Dangerous is terminated and restarted later</li>\n'
              '<li>CMDRHelper is closed in between</li>\n'
              '<li>The new journal session initially does not contain any mission events</li>\n'
              '</ul>\n'
              '<p>Only a documented mission event changes the saved state.</p>\n'
              '\n'
              '<h3>Several commanders</h3>\n'
              '<p>Missions are strictly separated by commander.</p>\n'
              '<p>A mission event is only assigned to the commander whose journal session has been '
              'uniquely identified. Missions of another commander may not be displayed or '
              'modified.</p>\n'
              '\n'
              '<h3>Orphaned or no longer valid missions</h3>\n'
              '<p>If older journal data or a previous import keeps a mission open even though it '
              'no longer exists in the game, the existing orphan mission reset/cleanup feature can '
              'be used.</p>\n'
              '<p>This function should only be used if it is clear that the displayed mission is '
              'no longer active.</p>\n'
              '\n'
              '<h3>Online Services</h3>\n'
              '<p>Supported mission events can additionally be transmitted to Inara if a valid and '
              'activated Inara access is set up for the active journal FID.</p>\n'
              '<p>A missing or unreachable Inara connection does not affect local mission '
              'storage.</p>\n'
              '\n'
              '<h3>Tip</h3>\n'
              '<p>If a mission does not appear or shows an incorrect status, first check whether '
              'Elite Dangerous has already written the corresponding mission event to the '
              'journal.</p>\n'
              '<p>CMDRHelper can only display information that the journal actually provides or '
              'that has already been stored from previous unique mission events.</p>'),
 'explorer': ('Explorer',
              '<h2>Explorer</h2>\n'
              '<p>The Explorer evaluates the systems and celestial bodies discovered and scanned '
              'by the active commander. It combines your own Elite Dangerous journal data with '
              'already available additional information and displays exploration, cartography, '
              'biological/geological signals and surface mining data together.</p>\n'
              '\n'
              '<h3>Current system</h3>\n'
              '<p>The current level of knowledge about the system is summarized in the upper '
              'area.</p>\n'
              '<p>These include, among others:</p>\n'
              '<ul>\n'
              '<li>well-known and even recorded bodies in the journal</li>\n'
              '<li>existing signals</li>\n'
              '<li>Scan values</li>\n'
              '<li>cartography value already achieved</li>\n'
              '<li>possible total value if fully mapped</li>\n'
              '<li>BIO status and estimated BIO values</li>\n'
              '<li>Cartography and BIO data that have not yet been submitted</li>\n'
              '</ul>\n'
              '<p>The values \u200b\u200bshown are based on the actually available data. Missing '
              'information is not presented as a separate discovery.</p>\n'
              '\n'
              '<h3>System map</h3>\n'
              '<p>The system map graphically represents stars, planets, moons and other known '
              'bodies in the current system.</p>\n'
              '<p>A body can be clicked to open its detailed view.</p>\n'
              '<p>The display shows, among other things, body type, distance and – if available – '
              'scan and cartography values \u200b\u200bas well as special exploration '
              'properties.</p>\n'
              '\n'
              '<h3>ORGANIC ×N</h3>\n'
              '<p>BIO ×N denotes the number of biological signals of a body reported by the '
              'game.</p>\n'
              '<p>The number initially only indicates how many biological signals or genera were '
              'reported. It does not automatically mean that all biological species have already '
              'been found or analyzed.</p>\n'
              '<p>Actual own organic discoveries are kept separately.</p>\n'
              '\n'
              '<h3>GEO ×N</h3>\n'
              '<p>GEO ×N shows the number of geological signals of a body reported by the '
              'game.</p>\n'
              '<p>These can include, for example, geological features such as fumaroles or '
              'geysers. CMDRHelper only displays the information that appears from the existing '
              'journal/body data.</p>\n'
              '\n'
              '<h3>ABBAU ×N</h3>\n'
              '<p>ABBAU ×N shows the number of planetary mining sites of a body reported by Elite '
              'Dangerous.</p>\n'
              '<p>Example:</p>\n'
              '<p><b>ABBAU ×24</b></p>\n'
              '<p>means that 24 planetary mining sites have been reported for this body.</p>\n'
              '<p>The number does not say which raw material can be extracted at a single '
              'location.</p>\n'
              '\n'
              '<h3>Own mining finds</h3>\n'
              '<p>If the commander has actually carried out surface mining with the Rhino, the '
              'CMDRHelper stores the personal findings documented separately.</p>\n'
              '<p>A distinction is made between:</p>\n'
              '<ul>\n'
              '<li>actually obtained commodities, e.g. B. Copper in tons</li>\n'
              '<li>secondary materials collected during mining</li>\n'
              '<li>general surface materials of the body</li>\n'
              '</ul>\n'
              '<p>An example of a personal find would be:</p>\n'
              '<p><b>Copper – 56 t</b></p>\n'
              '<p>This information means that this commander actually extracted 56 t of copper '
              'there.</p>\n'
              '<p>The personal mining finds are saved for each commander and are not mixed with '
              'the finds of other commanders.</p>\n'
              '\n'
              '<h3>Body surface materials</h3>\n'
              '<p><code>Scan.Materials</code>describes the general surface material composition of '
              'a body.</p>\n'
              '<p>For example, iron, nickel, sulfur or other materials can be displayed with '
              'percentage values.</p>\n'
              '<p>These values \u200b\u200bshould not be confused with the raw materials of a '
              'planetary mining depot. Frontier does not provide any documented direct association '
              'between these general body materials and the contents of an individual mining site '
              'in the Journal.</p>\n'
              '\n'
              '<h3>Terraforming</h3>\n'
              '<p>The symbol or label for terraforming shows that a body is considered a '
              'terraforming candidate based on the available data.</p>\n'
              '\n'
              '<h3>First discovery</h3>\n'
              '<p>The first discovery indicator identifies bodies for which, according to the '
              'available data, a first discovery is possible or has been documented accordingly by '
              "the body's own journal.</p>\n"
              '<p>The final rating is based on the conditions reported by Elite Dangerous or the '
              'available data.</p>\n'
              '\n'
              '<h3>First mapping</h3>\n'
              '<p>CMDRHelper distinguishes between:</p>\n'
              '<ul>\n'
              '<li>First mapping may be available</li>\n'
              '<li>mapped by the commander</li>\n'
              '<li>First mapping claimed by the commander</li>\n'
              '</ul>\n'
              '<p>This makes it possible to see whether a body has already been mapped and whether '
              'your commander claims first mapping status.</p>\n'
              '\n'
              '<h3>Country bar</h3>\n'
              '<p>The landability indicator identifies bodies on which, according to known data, '
              'landing is possible.</p>\n'
              '\n'
              '<h3>Gold frames / valuable bodies</h3>\n'
              '<p>Particularly valuable bodies can be highlighted in the explorer display.</p>\n'
              '<p>The gold frame serves as a quick visual orientation for bodies above the value '
              'threshold provided in CMDRHelper.</p>\n'
              "<p>It does not replace the detailed display of the body's value.</p>\n"
              '\n'
              '<h3>List of values</h3>\n'
              '<p>The Value List provides a more compact view of known bodies and their '
              'exploration/cartography values.</p>\n'
              '<p>It is particularly suitable for quickly comparing interesting or valuable bodies '
              'in a system.</p>\n'
              '\n'
              '<h3>ORGANIC / GEO / DEGRADATION</h3>\n'
              '<p>This view groups bodies with biological, geological or planetary degradation '
              'signals.</p>\n'
              '<p>This means that interesting bodies do not have to be searched for individually '
              'in the complete system map.</p>\n'
              '<p>If you have your own surface mining data, your personal mining finds can also be '
              'visible.</p>\n'
              '\n'
              '<h3>Body detail</h3>\n'
              '<p>Clicking on a body opens the detailed view.</p>\n'
              '<p>As far as is known, the following can appear there:</p>\n'
              '<ul>\n'
              '<li>Body Type</li>\n'
              '<li>mass</li>\n'
              '<li>distance</li>\n'
              '<li>Gravity</li>\n'
              '<li>atmosphere</li>\n'
              '<li>Landability</li>\n'
              '<li>Terraforming status</li>\n'
              '<li>BIO/GEO signals</li>\n'
              '<li>planetary mining sites</li>\n'
              '<li>Surface materials</li>\n'
              '<li>own mining finds</li>\n'
              '<li>Scan value</li>\n'
              '<li>cartography value</li>\n'
              '<li>current value</li>\n'
              '</ul>\n'
              '<p>Not every body has all the information.</p>\n'
              '\n'
              '<h3>BIO forecasts</h3>\n'
              '<p>CMDRHelper can estimate possible biological discoveries based on the existing '
              'data on suitable bodies.</p>\n'
              '<p>Predictions are not a guarantee that a particular species will actually be '
              'present. They serve as a decision-making aid for exploration.</p>\n'
              '<p>Estimated BIO values \u200b\u200bare also predictions and are treated separately '
              'from actual confirmed findings.</p>\n'
              '\n'
              '<h3>Not yet submitted</h3>\n'
              '<p>CMDRHelper maintains commander-related known cartography and BIO data that has '
              'not yet been submitted.</p>\n'
              '<p>Cartography sales and biological royalties are accounted for using the '
              'corresponding journal events.</p>\n'
              '<p>Cartography data that has already been sold should not appear as open again '
              'after reconstruction.</p>\n'
              '\n'
              '<h3>Show car</h3>\n'
              '<p>Supported live information such as Valuable Bodies, BIO Finds or Cargo can be '
              'automatically displayed using the switches in the left sidebar.</p>\n'
              '<p>These small live windows serve as additional hints while playing and do not '
              'replace the full Explorer view.</p>\n'
              '<p>“Cargo” shows the confirmed inventory of the Ship or SRV determined by the active Journal FID. SRV Cargo is never adopted as Ship Cargo; Limpets count towards the total load and are displayed separately in the Name | Quantity table.</p>\n'
              '\n'
              '<h3>Several commanders</h3>\n'
              '<p>Personal exploration results, cartography, BIO finds and own surface mining '
              'finds are assigned to the respective commander.</p>\n'
              '<p>Global astronomical properties of a body - for example the number of known '
              'planetary mining sites - remain properties of the body itself.</p>\n'
              '\n'
              '<h3>Tip</h3>\n'
              "<p>If you have an interesting body, it's worth clicking on the detailed view. This "
              'is the best place to differentiate between general body data, possible exploration '
              'results and actual finds documented by your own commander.</p>'),
 'chronicle': ('chronicle',
               '<h2>chronicle</h2>\n'
               "<p>The chronicle is the commander's personal travel and discovery history. It uses "
               'the permanently stored journal information to find systems that have already been '
               'visited, to spatially represent them and to search for known discoveries.</p>\n'
               '\n'
               '<h3>Systems visited</h3>\n'
               '<p>The Chronicle shows the systems visited and their locations in the galaxy known '
               'to the Commander.</p>\n'
               '<p>If available, the first and last visit as well as known body information are '
               'taken into account.</p>\n'
               '<p>The chronicle is therefore not just a map, but also a tool for finding previous '
               'travel destinations and discoveries.</p>\n'
               '\n'
               '<h3>3D map</h3>\n'
               '<p>The systems visited are spatially represented using their galactic X/Y/Z '
               'coordinates.</p>\n'
               '<p>The operating instructions are located directly above the map:</p>\n'
               '<ul>\n'
               '<li>Hold down the left mouse button → rotate view</li>\n'
               '<li>Hold down the middle mouse button → Zoom</li>\n'
               '<li>Hold down the right mouse button → move view</li>\n'
               '</ul>\n'
               '<p>The small axis display helps with orientation in space.</p>\n'
               '\n'
               '<h3>Current position</h3>\n'
               '<p>With “Current Position” the map view can be aligned or returned to the '
               'currently known location of the active commander.</p>\n'
               '<p>The prerequisite is that a valid current position is known for the '
               'commander.</p>\n'
               '\n'
               '<h3>Align</h3>\n'
               '<p>“Align” returns the map orientation to the intended basic orientation.</p>\n'
               '<p>This is helpful if the map has become confusing after being rotated or moved a '
               'lot.</p>\n'
               '\n'
               '<h3>Update timeline</h3>\n'
               '<p>“Update history” updates the display with the currently known data.</p>\n'
               '<p>The function does not change journal files or create new exploration data. It '
               'simply updates the history display based on the existing CMDRHelper data.</p>\n'
               '\n'
               '<h3>Free text search</h3>\n'
               '<p>Already known content can be searched using the “Search history…” field.</p>\n'
               '<p>The search takes into account – if available in the database – among other '
               'things:</p>\n'
               '<ul>\n'
               '<li>System names</li>\n'
               '<li>Body features</li>\n'
               '<li>biological data</li>\n'
               '<li>Materials</li>\n'
               '<li>Codex data</li>\n'
               '</ul>\n'
               '<p>The “Search” button only carries out this free text search.</p>\n'
               '<p>The separate DISMANTLING filters, on the other hand, are carried out with '
               '“Apply”.</p>\n'
               '\n'
               '<h3>Search results</h3>\n'
               '<p>Hits are displayed in the existing results list below the chronicle card.</p>\n'
               '<p>Depending on the type of hit, system and body as well as additional information '
               'may appear.</p>\n'
               '<p>A hit can be used to find the corresponding system or body that is already '
               'known and to open the existing detailed information.</p>\n'
               '\n'
               '<h3>Planetary mining sites</h3>\n'
               '<p>The filter “Planetary mining sites” can be used to specifically search for '
               'known bodies for which Elite Dangerous has reported planetary mining sites.</p>\n'
               '<p>The underlying display corresponds to that known from Explorer:</p>\n'
               '<p><b>ABBAU ×N</b></p>\n'
               '<p>The number belongs to the body itself and is not related to the commander.</p>\n'
               '\n'
               '<h3>At least</h3>\n'
               '<p>Using “At least” you can specify the minimum number of planetary mining '
               'locations a body should have.</p>\n'
               '<p>Example:</p>\n'
               '<p><b>At least 20</b></p>\n'
               '<p>only shows known bodies with at least:</p>\n'
               '<p><b>ABBAU ×20</b></p>\n'
               '<p>This makes it possible to specifically locate particularly extensive mining '
               'areas.</p>\n'
               '\n'
               '<h3>Own mining finds</h3>\n'
               '<p>With “Own mining finds” the search is limited to bodies on which the commander '
               'in question has demonstrably carried out surface mining himself.</p>\n'
               '<p>This information comes from personal surface mining history and is strictly '
               'separated by commander.</p>\n'
               '<p>A body can therefore have global ABBAU ×N signals without its own commander '
               'having already removed anything there.</p>\n'
               '\n'
               '<h3>raw material</h3>\n'
               '<p>If “Own mining finds” is activated, the “Raw material” selection is also '
               'available.</p>\n'
               '<p>The list only contains commodities that the commander in question has actually '
               'already won from surface mining.</p>\n'
               '<p>This is not a theoretical list of all possible mining raw materials.</p>\n'
               '<p>For example, FABER38 may appear:</p>\n'
               '<ul>\n'
               '<li>All</li>\n'
               '<li>copper</li>\n'
               '</ul>\n'
               '<p>If additional raw materials are actually mined later, they will automatically '
               'appear in your personal selection.</p>\n'
               '\n'
               '<h3>Targeted search for raw materials</h3>\n'
               '<p>For example, if “Copper” is selected and then “Apply” is pressed, the history '
               'will only show bodies on which the commander in question has demonstrably mined '
               'copper.</p>\n'
               '<p>Example:</p>\n'
               '<p><b>Prua Hypai NV-E c28-66 / 2 — ABBAU ×24 — copper 56 t</b></p>\n'
               '<p>This means that the chronicle can be used as a personal location database: a '
               'raw material that has already been mined can be found again later.</p>\n'
               '\n'
               '<h3>All raw materials</h3>\n'
               '<p>With “Raw Material: All” all matching personal surface mining discoveries are '
               'taken into account.</p>\n'
               '<p>If several commodities are known on a body, they can be displayed together with '
               'the quantities they have obtained so far.</p>\n'
               '<p>Example:</p>\n'
               '<p><b>ABBAU ×24 — Helium-3 18 t, copper 56 t</b></p>\n'
               '<p>The quantities are the personal mining values \u200b\u200bof the respective '
               'commander, which are actually documented from journal events.</p>\n'
               '\n'
               '<h3>Combine filters</h3>\n'
               '<p>The mining filters can be combined with each other.</p>\n'
               '<p>For example:</p>\n'
               '<ul>\n'
               '<li>Planetary mining sites active</li>\n'
               '<li>At least 20</li>\n'
               '<li>Own mining finds active</li>\n'
               '<li>Raw material copper</li>\n'
               '</ul>\n'
               '<p>searches for known bodies with at least 20 planetary mining sites where the '
               'commander in question has already mined copper himself.</p>\n'
               '\n'
               '<h3>Apply</h3>\n'
               '<p>“Apply” only runs the visible mining filters.</p>\n'
               '<p>The “Search” button next to it is reserved for free text searches.</p>\n'
               '<p>This means that text search and mining filters are deliberately separated from '
               'each other.</p>\n'
               '\n'
               '<h3>Reset</h3>\n'
               '<p>“Reset” deletes the current free text search and also resets the mining filters '
               'to their initial state.</p>\n'
               '<p>The raw material selection jumps back to “All”.</p>\n'
               '\n'
               '<h3>Commander selection</h3>\n'
               '<p>The chronicle can display data from various well-known commanders.</p>\n'
               '<p>However, personal information such as your own mining finds and raw material '
               'lists are always evaluated separately for the commander actually being '
               'viewed.</p>\n'
               '<p>A commander does not see any mining discoveries in his raw material selection '
               'that belong exclusively to another commander.</p>\n'
               '\n'
               '<h3>All commanders</h3>\n'
               '<p>The map/chronicle display can take multiple commanders into account.</p>\n'
               '<p>This does not change the personal assignment of commander-related data. Global '
               'astronomical properties of a system or body remain shared, personal findings '
               'remain separate.</p>\n'
               '\n'
               '<h3>Search aid / legend</h3>\n'
               '<p>Additional information about the chronicle search and the meaning of the '
               'display can be accessed via “Search help / legend”.</p>\n'
               '<p>This context-related main help supplements the short operating instructions '
               'available there.</p>\n'
               '\n'
               '<h3>Tip</h3>\n'
               '<p>The chronicle is particularly suitable for finding interesting places that were '
               'discovered during a longer trip.</p>\n'
               '<p>For surface mining, for example, it can answer:</p>\n'
               '<p>“On which planet have I ever mined copper?”</p>\n'
               '<p>or:</p>\n'
               '<p>“Which of my known planets have a particularly high number of mining '
               'sites?”</p>'),
 'jump_tip': ('Jump tip',
              '<h2>Jump tip</h2>\n'
              '<p>The jump tip supports exploration by evaluating already known system data and '
              'highlighting interesting target systems.</p>\n'
              '<p>The function is intended as a decision-making aid. It does not guarantee that a '
              'recommended system actually contains rare or particularly valuable finds.</p>\n'
              '\n'
              '<h3>Basis of the evaluation</h3>\n'
              '<p>CMDRHelper uses existing journal and database information to evaluate known '
              'patterns in system names and system classes.</p>\n'
              '<p>Among other things, system abbreviations, already known body types and previous '
              'finds can be taken into account.</p>\n'
              '\n'
              '<h3>System abbreviation</h3>\n'
              '<p>Many procedurally generated systems in Elite Dangerous contain letter and number '
              'combinations that identify specific system groups.</p>\n'
              '<p>CMDRHelper can statistically evaluate these abbreviations and show in which '
              'groups interesting finds occurred more frequently in the data known to date.</p>\n'
              '\n'
              '<h3>Re-evaluate</h3>\n'
              '<p>With “Re-evaluate” the existing database is analyzed again.</p>\n'
              "<p>The commander's saved data is used. The function does not create new elite data "
              'or modify journal files.</p>\n'
              '\n'
              '<h3>Results list</h3>\n'
              '<p>The results list shows the most interesting system abbreviations or candidates '
              'according to the current evaluation.</p>\n'
              '<p>Depending on the existing database, there may be information about:</p>\n'
              '<ul>\n'
              '<li>interesting planetary classes</li>\n'
              '<li>biological discoveries</li>\n'
              '<li>Water worlds</li>\n'
              '<li>terraformable bodies</li>\n'
              '<li>other notable exploration results</li>\n'
              '</ul>\n'
              '<p>appear.</p>\n'
              '\n'
              '<h3>Probability instead of guarantee</h3>\n'
              '<p>A high value or a good ranking only means that a certain pattern was more often '
              'associated with interesting findings in the data evaluated so far.</p>\n'
              '<p>It is not a guarantee.</p>\n'
              '<p>A recommended system may still be completely uninteresting, while a low-rated '
              'system may contain valuable finds.</p>\n'
              '\n'
              '<h3>Own database</h3>\n'
              "<p>The jump tip works with the commander's already known data.</p>\n"
              '<p>The more systems and bodies are recorded over time, the larger the personal '
              'database for evaluation becomes.</p>\n'
              '<p>This means the ranking can change later.</p>\n'
              '\n'
              '<h3>Several commanders</h3>\n'
              '<p>Personal evaluations are handled on a commander-by-command basis.</p>\n'
              '<p>Data from another commander must not falsify the personal rating unnoticed.</p>\n'
              '<p>Global astronomical master data, on the other hand, can be shared as long as it '
              'does not represent commander-related personal findings.</p>\n'
              '\n'
              '<h3>Use in practice</h3>\n'
              '<p>The jumping tip is particularly suitable if there are several possible '
              'destinations to choose from and additional decision-making assistance is '
              'desired.</p>\n'
              '<p>It does not replace a complete route planner and does not calculate a safe, '
              'optimal route.</p>\n'
              '<p>The “Route planner” menu item is available for specific route planning.</p>\n'
              '\n'
              '<h3>Tip</h3>\n'
              '<p>Use the jump tip as an additional exploration aid:</p>\n'
              '<p>“According to my previous data, which system seems more interesting?”</p>\n'
              '<p>Not as a prediction:</p>\n'
              '<p>“There is guaranteed to be a specific find in this system.”</p>'),
 'route_planner': ('Route planner',
                   '<h2>Route planner</h2>\n'
                   '<p>The route planner supports planning longer trips by ship or Fleet Carrier. '
                   'CMDRHelper can use external route data from Spansh and prepare the planned '
                   'route for further use.</p>\n'
                   '\n'
                   '<h3>Start and finish</h3>\n'
                   '<p>A start and destination system are required for route calculation.</p>\n'
                   "<p>To the extent possible, CMDRHelper may use the Commander's current known "
                   'system as a starting point. Start and finish should be checked before '
                   'calculation.</p>\n'
                   '\n'
                   '<h3>Ship or Fleet Carrier</h3>\n'
                   '<p>The route planner differentiates between trips with a normal ship and with '
                   'a Fleet Carrier.</p>\n'
                   '<p>Both use different requirements and calculation methods. Therefore, the '
                   'appropriate route type must be selected before planning.</p>\n'
                   '\n'
                   '<h3>Ship route</h3>\n'
                   '<p>For a ship route, the jump properties known or entered for the active ship '
                   'are taken into account.</p>\n'
                   '<p>Depending on the available data, FSD data, ship data, mass, fuel and other '
                   'jump parameters can be incorporated into the planning.</p>\n'
                   '<p>A calculated route is a planning aid. Changes to the ship or its mass may '
                   'change the actual jump distance achievable in the game.</p>\n'
                   '\n'
                   '<h3>Fleet carrier route</h3>\n'
                   '<p>Fleet Carrier have different jumping rules than normal ships.</p>\n'
                   '<p>CMDRHelper uses the designated Spansh carrier planning for corresponding '
                   'routes.</p>\n'
                   '<p>The route is used to plan the jump sequence. Actual tritium consumption and '
                   'available range may also depend on mass and current carrier status.</p>\n'
                   '\n'
                   '<h3>Spansh</h3>\n'
                   '<p>For the actual route calculation, CMDRHelper can use the external service '
                   'Spansh.</p>\n'
                   '<p>The request is processed in the background so that the interface remains '
                   'operable during a longer calculation.</p>\n'
                   '<p>CMDRHelper has no influence on the availability or response time of the '
                   'external service.</p>\n'
                   '\n'
                   '<h3>calculation</h3>\n'
                   '<p>After starting a calculation, the request is passed on to the selected '
                   'route planner.</p>\n'
                   '<p>Depending on the route and service, the calculation may take some time. '
                   'During this time, no second identical calculation should be started '
                   'unnecessarily.</p>\n'
                   '\n'
                   '<h3>Result</h3>\n'
                   '<p>A successfully calculated route shows the intended systems or jump points '
                   'in their order.</p>\n'
                   '<p>Depending on the route type, additional information appears on distance, '
                   'jumps, fuel or tritium and other available route data.</p>\n'
                   '\n'
                   '<h3>Route and current commander</h3>\n'
                   '<p>The current system and ship can - as long as they are clearly known in the '
                   'active AppState - be used for pre-assignment or to support planning.</p>\n'
                   '<p>However, the actual route remains a plan and does not change any journal or '
                   'commander data.</p>\n'
                   '\n'
                   '<h3>CTSVision export</h3>\n'
                   '<p>Calculated fleet carrier routes can be exported as CSV for CTSVision.</p>\n'
                   '<p>This means that a carrier route planned in CMDRHelper can then be used in '
                   'CTSVision for jump control or route processing there.</p>\n'
                   '<p>The export does not change the route in CMDRHelper.</p>\n'
                   '\n'
                   '<h3>CSV file</h3>\n'
                   '<p>The exported file contains the route data required for CTSVision in the '
                   'intended order.</p>\n'
                   '<p>The file should not be structurally changed in an uncontrolled manner after '
                   'export if it is then to be read in by CTSVision.</p>\n'
                   '\n'
                   '<h3>Errors and external services</h3>\n'
                   '<p>If Spansh cannot be reached or the service returns an error, CMDRHelper '
                   'displays a corresponding error message.</p>\n'
                   '<p>An error in online route calculation does not change local commander or '
                   'journal data.</p>\n'
                   '\n'
                   '<h3>Route planner and jumping tip</h3>\n'
                   '<p>Jump tip and route planner fulfill different tasks:</p>\n'
                   '<ul>\n'
                   '<li>Jump tip evaluates possible interesting exploration targets based on '
                   'existing data.</li>\n'
                   '<li>Route planner calculates a specific route between start and '
                   'destination.</li>\n'
                   '</ul>\n'
                   '<p>A good jumping tip is therefore not automatically part of an optimal '
                   'route.</p>\n'
                   '\n'
                   '<h3>Several commanders</h3>\n'
                   '<p>If commander-related data such as current system or ship is used, this '
                   'comes from the active live AppState and must be clearly assigned there.</p>\n'
                   '<p>Simply looking at another commander in the CMDR view does not switch the '
                   'route planner to their system or ship.</p>\n'
                   '<p>A route calculation itself does not change the personal data of another '
                   'commander.</p>\n'
                   '\n'
                   '<h3>Tip</h3>\n'
                   '<p>Before a long trip, always check again:</p>\n'
                   '<ul>\n'
                   '<li>Starting system</li>\n'
                   '<li>Target system</li>\n'
                   '<li>Route type ship/carrier</li>\n'
                   '<li>for ship routes, the underlying ship, FSD and jump parameters</li>\n'
                   '<li>for carrier routes, the available tritium reserve</li>\n'
                   '</ul>\n'
                   '<p>For fleet carrier trips, it is advisable to also plan sufficient reserves '
                   'for the return journey or unplanned detours.</p>'),
 'images': ('Pictures',
            '<h2>Pictures</h2>\n'
            '<p>The “Images” section manages the screenshots taken with Elite Dangerous. '
            'CMDRHelper can automatically recognize new recordings, process them and store them in '
            'a gallery based on the commander.</p>\n'
            '\n'
            '<h3>Source folder</h3>\n'
            '<p>The source folder is the folder where Elite Dangerous saves its screenshots in BMP '
            'format.</p>\n'
            '<p>CMDRHelper can monitor this folder for new BMP files. For automatic processing to '
            'work, the correct screenshot folder must be set.</p>\n'
            '\n'
            '<h3>Destination folder</h3>\n'
            '<p>The destination folder is the common root folder for the images processed by '
            'CMDRHelper.</p>\n'
            '<p>The user sets this root folder. CMDRHelper automatically creates the required '
            'commander-related subfolders during processing.</p>\n'
            '\n'
            '<h3>Automatic processing</h3>\n'
            '<p>If “Automatically convert” is activated and valid source and destination folders '
            'are set, CMDRHelper regularly checks the source folder for new BMP screenshots.</p>\n'
            '<p>When activated, existing BMP files are initially marked as known and are not '
            'automatically converted without being asked. The separate function for converting '
            'existing BMPs is available for this.</p>\n'
            '<p>A new file is not enqueued until it has the same non-zero size in two consecutive '
            'checks. As a result, a write operation that is still in progress is not processed '
            'immediately.</p>\n'
            '\n'
            '<h3>Image conversion</h3>\n'
            '<p>As a source, CMDRHelper processes BMP files. “PNG” or “JPG” can be selected as the '
            'target format.</p>\n'
            '<p>JPG files are saved at quality level 95. PNG files are saved in an optimized '
            'manner.</p>\n'
            '<p>By default, the original BMP file is retained. If “Delete BMP after conversion” is '
            'activated, the source BMP will only be deleted after the target image has been '
            'successfully saved.</p>\n'
            '\n'
            '<h3>Brighten image</h3>\n'
            '<p>The brightening is adjusted from 0 to 50 percent using a slider and a linked '
            'number field. The setting is saved.</p>\n'
            '<p>It is automatically applied during every conversion started thereafter - both for '
            'newly monitored and manually initiated existing BMP files. 0 percent takes over the '
            'original brightness; higher values \u200b\u200bincrease the brightness of the '
            'generated PNG or JPG image accordingly.</p>\n'
            '<p>The function is not a pure preview and is not subsequently applied to an image '
            'selected in the gallery. The changed brightness is saved in the new target file.</p>\n'
            '<p>The source BMP remains unchanged unless deletion of the BMP file is also '
            'activated. Journal, commander and exploration data are not changed.</p>\n'
            '\n'
            '<h3>Commander related storage</h3>\n'
            '<p>New screenshots are assigned to the actual playing Commander based on the journal '
            'identity present in the active live AppState.</p>\n'
            '<p>The folder structure contains commander name and Frontier ID, for example:</p>\n'
            '<p><b>FABER38_F12520967/</b></p>\n'
            '<p>The FID keeps the assignment clear even with multiple commanders. This allows two '
            'commanders with the same name to be distinguished.</p>\n'
            '\n'
            '<h3>filenames</h3>\n'
            '<p>New processed images receive a name with the time of capture, commander name and - '
            'if available - the star system known when queuing.</p>\n'
            '<p>Example:</p>\n'
            '<p><b>2026-09-04_13-18-22_FABER38_Prua-Hypai-RB-D-c29-71.png</b></p>\n'
            '<p>The FID is in the commander-related folder name, not again in the image file '
            'name.</p>\n'
            '\n'
            '<h3>Secure filenames</h3>\n'
            '<p>CMDRHelper sanitizes commander and system names for use as file and folder '
            'components.</p>\n'
            '<p>Illegal control and Windows characters are replaced, whitespace is unified, '
            'problematic periods or trailing spaces are removed, and reserved Windows names such '
            'as CON or NUL are secured.</p>\n'
            '\n'
            '<h3>Recording time</h3>\n'
            '<p>For naming, CMDRHelper uses the modification time of the stable recognized BMP '
            'file. Only if this cannot be read will the current time be used.</p>\n'
            '<p>This means that the name usually depends on the source file and not on the '
            'subsequent conversion time.</p>\n'
            '\n'
            '<h3>Multiple images in the same second</h3>\n'
            '<p>If the intended file name already exists or is reserved for an ongoing conversion, '
            'CMDRHelper continuously adds it<code>_2</code>,<code>_3</code>,<code>_4</code>and so '
            'forth.</p>\n'
            '<p>This means that another screenshot with the same timestamp will not overwrite an '
            'existing target image.</p>\n'
            '\n'
            '<h3>Commander change during processing</h3>\n'
            '<p>Commander, FID and system are captured together when queuing a screenshot.</p>\n'
            '<p>A later change of commander does not change the assignment of this already waiting '
            'image. This means that a screenshot of FABER38 is not subsequently written to the '
            'folder of another commander.</p>\n'
            '\n'
            '<h3>gallery</h3>\n'
            '<p>The gallery shows PNG, JPG and JPEG files from the directories associated with the '
            'selected filter. New, deleted or moved images are regularly detected.</p>\n'
            '<p>The gallery filter does not change the storage location or commander assignment of '
            'the files.</p>\n'
            '\n'
            '<h3>Current commander</h3>\n'
            '<p>The Current Commander filter shows images from the folder of the commander '
            'currently viewed in the CMDR view.</p>\n'
            '<p>The commander in question only determines the gallery display. On the other hand, '
            'assigning a new live screenshot uses the journal identity active when enqueuing.</p>\n'
            '\n'
            '<h3>All commanders</h3>\n'
            '<p>The “All Commanders” filter shows the images from the valid subfolders of all '
            'known commanders together. The special folder for recordings without recognized '
            'identity is also taken into account.</p>\n'
            '<p>The files are not moved or merged.</p>\n'
            '\n'
            '<h3>Not assigned</h3>\n'
            '<p>The Unassigned filter shows supported image files located directly in the shared '
            'target root folder.</p>\n'
            '<p>In particular, older images without commander-related subfolders remain visible. '
            "CMDRHelper doesn't try to guess their affiliation after the fact.</p>\n"
            '\n'
            '<h3>Existing images</h3>\n'
            '<p>Existing images in the root folder are not automatically moved or renamed.</p>\n'
            '<p>They remain accessible via “Unassigned” as long as they are available as PNG, JPG '
            'or JPEG.</p>\n'
            '\n'
            '<h3>Select and view image</h3>\n'
            '<p>A simple click on a preview image shows the image scaled in the preview area and '
            'displays its file name.</p>\n'
            '<p>A double click opens the file with the operating system application set for '
            'images.</p>\n'
            '<p>Multiple images can be marked at the same time. When you change the window size, '
            'the preview of the current image is rescaled to fit.</p>\n'
            '\n'
            '<h3>Delete image</h3>\n'
            '<p>Marked images can be deleted using “Delete selected” or the Delete key. Before '
            'deleting, a security query appears; Without a selection, the necessary selection is '
            'first pointed out.</p>\n'
            '<p>Only the selected PNG/JPG/JPEG target files are deleted from the directories of '
            'the current gallery filter. The original BMP source file is not affected.</p>\n'
            '\n'
            '<h3>Open target folder</h3>\n'
            '<p>“Open target folder” opens the storage location in the file manager and creates '
            'the shared root folder if necessary.</p>\n'
            '<p>The “Current Commander” filter opens its existing Commander subfolder. If it does '
            'not yet exist or another filter is active, the shared root folder will be '
            'opened.</p>\n'
            '\n'
            '<h3>Security of image paths</h3>\n'
            '<p>Before deleting, CMDRHelper checks the canonical path of each file. It must be '
            'within the configured target folder and directly in a directory permitted by the '
            'current gallery filter.</p>\n'
            '<p>Symbolic links are not used as commander folders or gallery images and are not '
            'deleted via the gallery. Paths outside the target area and traversal paths are '
            'rejected.</p>\n'
            '\n'
            '<h3>If no commander was detected</h3>\n'
            '<p>If Commander and FID are missing when queuing a new recording, the file will not '
            'be put on hold and will not be assigned to a known Commander.</p>\n'
            '<p>It will be in the subfolder<b>UNKNOWN_UNKNOWN/</b>processed; the file name also '
            'used for the Commander<b>UNKNOWN</b>. This folder can be viewed through All '
            'Commanders, not through the Unallocated root folder filter.</p>\n'
            '\n'
            '<h3>Several commanders</h3>\n'
            '<p>Two separate rules apply to image management:</p>\n'
            '<ul>\n'
            '<li><b>Save new images:</b>The active journal identity with Commander and FID when '
            'enqueued determines the destination folder.</li>\n'
            '<li><b>View images:</b>The commander viewed or the selected gallery filter determines '
            'the visible images.</li>\n'
            '</ul>\n'
            '<p>This means that the gallery of another commander can be viewed while FABER38 is '
            'being played without new screenshots ending up in the folder of the commander in '
            'question.</p>\n'
            '\n'
            '<h3>Tip</h3>\n'
            '<p>A shared screenshot root folder is sufficient. CMDRHelper automatically separates '
            'newly processed images into Commander and FID.</p>\n'
            '<p>With "Current Commander", "All Commanders" and "Unassigned" you can switch between '
            'personal gallery, the subfolders of all commanders and older images in the root '
            'folder.</p>\n'
            '<p>Higher brightness can help with dark photos; it affects the newly created target '
            'image during the conversion.</p>'),
 'commander_view': ('CMDR view',
                    '<h2>CMDR view</h2>\n'
                    "<p>The CMDR view summarizes a commander's permanently stored personal "
                    'information.</p>\n'
                    '<p>It also allows you to switch between the CMDRHelper known commanders and '
                    'view their own data. Personal information is separated using the Frontier ID '
                    '(FID).</p>\n'
                    '\n'
                    '<h3>Select Commander</h3>\n'
                    '<p>If several commanders are known, you can use the selection above to '
                    'determine whose saved information is displayed. This commander is the '
                    'considered commander.</p>\n'
                    '<p>The display marks it as either “Live Active” or “View Only”.</p>\n'
                    '\n'
                    '<h3>Considered Commander and Live Commander</h3>\n'
                    '<p>Selecting another commander in the CMDR view does not make it the active '
                    'journal commander.</p>\n'
                    '<p>The live commander is determined exclusively from the currently uniquely '
                    'identified Elite Dangerous journal session. This way the history of another '
                    'commander can be viewed while Elite Dangerous continues to run with '
                    'FABER38.</p>\n'
                    '\n'
                    '<h3>Frontier ID (FID)</h3>\n'
                    '<p>The FID is the stable Frontier identifier of a commander.</p>\n'
                    '<p>CMDRHelper uses it and the internal commander ID resolved from it to '
                    'securely separate personal data. Commanders with similar or identical names '
                    'also remain separated.</p>\n'
                    '\n'
                    '<h3>Overview</h3>\n'
                    '<p>The “Overview” tab only shows permanently saved information for the '
                    'commander in question:</p>\n'
                    '<ul>\n'
                    '<li>Commander name, FID and status “Live active” or “View only”</li>\n'
                    '<li>first and last known time</li>\n'
                    '<li>Number of systems visited, bio and geo discoveries, codex entries and '
                    'cartography sales</li>\n'
                    '<li>Last known location and number of open missions</li>\n'
                    '<li>current or last ship</li>\n'
                    '<li>Fleet Carrier and carrier location</li>\n'
                    '<li>Assets</li>\n'
                    '<li>open biodata and open cartographic data including existing '
                    'estimates</li>\n'
                    '</ul>\n'
                    '\n'
                    '<h3>Assets/Credits</h3>\n'
                    '<p>The “Assets” field shows the most recently saved credit balance of the '
                    'commander in question from an appropriate journal event, formatted as, for '
                    'example<b>1,234,567 Cr</b>.</p>\n'
                    '<p>CMDRHelper does not add fictitious income or expenses if there is no new, '
                    'secure journal status.</p>\n'
                    '\n'
                    '<h3>Mercenary coins</h3>\n'
                    '<p>The mercenary coins come from the MercCoins fields provided by Elite '
                    'Dangerous<code>Statistics → Bank_Account</code>and are saved '
                    'commander-related as a Frontier snapshot.</p>\n'
                    '<p>Visible are:</p>\n'
                    '<ul>\n'
                    '<li>Current</li>\n'
                    '<li>Total spent</li>\n'
                    '<li>Engineering</li>\n'
                    '<li>equipment</li>\n'
                    '<li>Reported by Frontier: earned overall</li>\n'
                    '</ul>\n'
                    '\n'
                    '<h3>Current and editions</h3>\n'
                    '<p>“Current” shows<code>MercCoins_Current</code>. “Total Spent” takes '
                    'over<code>MercCoins_Total_Spent</code>.</p>\n'
                    '<p>“Engineering” and “Equipment” show the shares reported separately by '
                    'Frontier<code>MercCoins_Spent_On_Engineering</code>and<code>MercCoins_Spent_On_MercGear</code>.</p>\n'
                    '<p>For FABER38, for example, a current inventory of<b>1,275</b>, in '
                    'total<b>220</b>spent and away<b>220</b>reported for engineering.</p>\n'
                    '\n'
                    '<h3>Overall deserved</h3>\n'
                    '<p>“Reported by Frontier: earned overall” '
                    'shows<code>MercCoins_Total_Earned</code>. CMDRHelper does not calculate its '
                    'own balance sheet from this.</p>\n'
                    "<p>Frontier's cumulative value does not have to mathematically match the "
                    'current inventory and reported expenses. For example, 1,275 current, 25 total '
                    'earned, and 220 total spent may be reported at the same time.</p>\n'
                    '<p>CMDRHelper does not correct these values, but displays the individual '
                    'Frontier counters unchanged.</p>\n'
                    '\n'
                    '<h3>Why not have your own MercCoins balance sheet?</h3>\n'
                    '<p>Elite Dangerous does not provide a unique journal entry record for each '
                    'individual receipt or expenditure of mercenary coins. The MercCoins appear as '
                    'totals in Statistics.</p>\n'
                    '<p>A self-calculated booking history would therefore not be reliable. '
                    'CMDRHelper saves the latest known Frontier snapshot instead.</p>\n'
                    '\n'
                    '<h3>Missions</h3>\n'
                    '<p>The “Missions” tab shows the saved missions of the commander in question '
                    'as a table with status, mission name, objective, expiration time and '
                    'reward.</p>\n'
                    '\n'
                    '<h3>exploration</h3>\n'
                    '<p>The Exploration tab shows open biodata, open cartography data, '
                    'biodiscoveries, first footfalls, self-mapped and efficiently mapped bodies, '
                    'and the number of systems visited.</p>\n'
                    '<p>The dedicated “Chronicle” tab within the CMDR view is currently still a '
                    'placeholder. The complete chronicle can be found in the main menu item of the '
                    'same name.</p>\n'
                    '\n'
                    '<h3>Ships/Fleet</h3>\n'
                    '<p>The “Ships” tab initially shows the active or most recently used ship with '
                    'ship name, ship type, location and ShipID.</p>\n'
                    '<p>The saved ships of the commander in question appear below them as '
                    'expandable cards. They can be sorted ascending or descending by:</p>\n'
                    '<ul>\n'
                    '<li>last or currently used</li>\n'
                    '<li>Ship name or ship type</li>\n'
                    '<li>maximum jumping range</li>\n'
                    '<li>Cargo capacity or empty mass</li>\n'
                    '<li>last known location or time</li>\n'
                    '</ul>\n'
                    '<p>You can also filter for all ships, ships with a vehicle hangar or ships '
                    'with a fighter hangar.</p>\n'
                    '\n'
                    '<h3>Ship details</h3>\n'
                    '<p>An opened ship map shows - if saved - ship ID, ShipID, location, last '
                    'time, maximum jump range, FSD and Guardian booster, mass, cargo and tank '
                    'capacities as well as loadout time and status.</p>\n'
                    '<p>If module data is available, vehicle and fighter hangar, shield generator '
                    'and shield booster, Guardian shield reinforcements, weapons, hull and module '
                    'reinforcements and passenger cabins are also summarized.</p>\n'
                    '<p>The loadout status can be complete, incomplete or stale. Missing '
                    'information is displayed as “–” and is not made up.</p>\n'
                    '\n'
                    '<h3>Fleet Carrier</h3>\n'
                    '<p>For a saved custom Fleet Carrier, the view shows carrier name, call sign, '
                    'carrier ID, last location and the time of the last update.</p>\n'
                    '\n'
                    '<h3>Persistent commander state</h3>\n'
                    '<p>Important commander information remains permanently saved. This allows '
                    'known values \u200b\u200bto be displayed again after a restart of CMDRHelper '
                    'or Elite Dangerous without fully evaluating each journal again.</p>\n'
                    '<p>New unique journal events update the saved state.</p>\n'
                    '\n'
                    '<h3>Historical reconstruction</h3>\n'
                    '<p>For functions that are added later, CMDRHelper can search existing journal '
                    'areas that are clearly assigned to a commander once for information that is '
                    'already known.</p>\n'
                    '<p>For example, older MercCoins snapshots can be adopted. Repeated checks are '
                    'not intended to produce duplicate data and do not alter normal journal read '
                    'positions.</p>\n'
                    '\n'
                    '<h3>Several commanders</h3>\n'
                    '<p>In particular, the following remain separate in terms of commanders:</p>\n'
                    '<ul>\n'
                    '<li>Assets and Missions</li>\n'
                    '<li>own cartography and organic finds</li>\n'
                    '<li>Surface mining history and mercenary coins</li>\n'
                    '<li>Online credentials</li>\n'
                    '<li>commander related screenshots</li>\n'
                    '</ul>\n'
                    '<p>Global astronomical properties of a system or body, however, can be used '
                    'together.</p>\n'
                    '\n'
                    '<h3>Impact on other views</h3>\n'
                    '<p>Changing the commander in question updates the CMDR view itself, the '
                    'personal mining raw material selection of the chronicle and, with the '
                    'appropriate filter, the screenshot gallery.</p>\n'
                    '<p>It does not replace the actual live commander for journal processing or '
                    'online uploads.</p>\n'
                    '\n'
                    '<h3>Inara and EDSM</h3>\n'
                    '<p>Inara and EDSM accesses are managed separately per commander and FID, '
                    'respectively.</p>\n'
                    '<p>Simply looking at a commander does not start a transmission with their '
                    'API-Key. Only the active journal FID is relevant for live uploads.</p>\n'
                    '<p>The access data is managed under “Settings” in the online services '
                    'area.</p>\n'
                    '\n'
                    '<h3>Tip</h3>\n'
                    '<p>Use the CMDR view if you want to view saved personal information for a '
                    'specific commander.</p>\n'
                    '<p><b>CMDR view = Who do I want to view?</b></p>\n'
                    '<p><b>Active Journal-FID = Who is actually playing right now?</b></p>\n'
                    '<p>This separation prevents personal data or online uploads from different '
                    'commanders from being mixed together.</p>'),
 'settings': ('Settings',
              '<h2>Settings</h2>\n'
              '<p>The “Settings” area determines how CMDRHelper works with Elite Dangerous, '
              'journal files, database, online services, interface and updates.</p>\n'
              '<p>Changes to credentials and paths should be made carefully. Commander-related '
              'settings are managed separately by Frontier ID if necessary.</p>\n'
              '\n'
              '<h3>journal</h3>\n'
              '<p>The journal folder is one of the most important settings. It must point to the '
              'folder where Elite Dangerous the<code>Journal*.log</code>files of the Windows or '
              'Proton profile used.</p>\n'
              '<p>The journals provide, among other things:</p>\n'
              '<ul>\n'
              '<li>Commander identity, location and travel</li>\n'
              '<li>Missions, ships and assets</li>\n'
              '<li>Exploration, cartography and BIO data</li>\n'
              '<li>Surface mining, mercenary coins and other supported states</li>\n'
              '</ul>\n'
              '\n'
              '<h3>Journal display and operation</h3>\n'
              '<p>The journal group shows the folder set, the number of journals found, the oldest '
              'and newest journals, the name of the newest file and the time of the last read '
              'entry.</p>\n'
              '<p>“Select journal folder” changes the folder. “Read now” triggers the normal '
              'update immediately.</p>\n'
              '<p>Clearly identifiable sessions are assigned using FID. New complete entries are '
              'processed incrementally; Secure reading positions prevent each journal from being '
              'unnecessarily reread in its entirety the next time it is started.</p>\n'
              '\n'
              '<h3>database</h3>\n'
              '<p>CMDRHelper permanently stores required data in a local SQLite database. This '
              'includes global system and body data as well as information explicitly assigned to '
              'a commander.</p>\n'
              '<p>The settings page shows statistics about the saved data. The database should not '
              'be edited manually while CMDRHelper is running.</p>\n'
              '\n'
              '<h3>Import journal archive</h3>\n'
              '<p>“Import journal archive” completely compares the journal files of the set '
              'journal folder with the database. Already known journal areas are taken into '
              'account based on the saved import information and are not blindly duplicated as new '
              'data.</p>\n'
              '<p>During a manually visible import, the progress, number and currently processed '
              'file are displayed. After completion, CMDRHelper reports imported or already known '
              'data or an error.</p>\n'
              '<p>The archive import also serves to relearn supported historical information from '
              'clearly assigned journals.</p>\n'
              '\n'
              '<h3>Commander related data</h3>\n'
              '<p>CMDRHelper separates personal information based on the FID and the associated '
              'internal Commander ID. These include, but are not limited to, missions, assets, '
              'MercCoins, personal exploration and online access.</p>\n'
              '<p>An unknown or ambiguous journal session may not be arbitrarily assigned to a '
              'commander.</p>\n'
              '\n'
              '<h3>Online Services</h3>\n'
              '<p>CMDRHelper supports EDSM and Inara. Both accesses are processed and saved '
              'separately for each known commander or each FID.</p>\n'
              '<p>The selection in the settings only determines whose access is currently being '
              'edited or tested. Only the commander clearly identified by the active journal '
              'session is allowed to send live.</p>\n'
              '\n'
              '<h3>EDSM access for</h3>\n'
              '<p>“EDSM access for:” selects the commander to be edited. The selection will show '
              '“set up” or “not set up” depending on whether a API-Key is stored.</p>\n'
              '<p>Visible are commander name, hidden API-Key field, “Use EDSM”, a connection test '
              'and its last test status.</p>\n'
              '<p>Each commander needs their own appropriate EDSM access. The selection does not '
              'switch the live uploader to this commander.</p>\n'
              '\n'
              '<h3>Use and test EDSM</h3>\n'
              '<p>“Use EDSM” enables or disables the service for the selected FID. Missing or '
              'deactivated credentials do not affect local journal processing.</p>\n'
              '<p>“Test EDSM connection” checks the access data currently visible in the form. A '
              'successful test confirms the connection, but does not change the active journal FID '
              'or live commander.</p>\n'
              '\n'
              '<h3>Inara access for</h3>\n'
              '<p>“Inara Access for:” follows the same multi-CMDR principle. Activation, Inara '
              'commander name and API-Key are saved separately for each FID.</p>\n'
              '<p>Here too, the selection shows “set up” or “not set up”. A key from one commander '
              'is not automatically used for another commander.</p>\n'
              '\n'
              '<h3>Use and test Inara</h3>\n'
              '<p>With Inara set up and enabled for the active journal FID, CMDRHelper can '
              'transmit the supported travel, location, mission and ship events. Not every journal '
              'event is sent to Inara.</p>\n'
              '<p>“Test Inara connection” checks the currently visible access data without '
              'changing the live commander.</p>\n'
              '\n'
              '<h3>Inara outbox</h3>\n'
              '<p>Supported Inara events are persistently flagged in an outbox before network '
              'transmission.</p>\n'
              '<p>Temporary errors allow these entries to be preserved for later attempts. The '
              'worker only processes the outbox of the uniquely active journal FID; Entries from '
              'other commanders are not included.</p>\n'
              '\n'
              '<h3>Online status in the header</h3>\n'
              '<p>EDSM currently shows:</p>\n'
              '<ul>\n'
              '<li><b>EDSM</b>– cannot be used or deactivated for the active FID</li>\n'
              '<li><b>EDSM is waiting</b>– set up and without ongoing transmission</li>\n'
              '<li><b>EDSM transmission</b>– the last EDSM processing run ended without errors; '
              'The tooltip states whether events were sent, journal data was processed or no new '
              'data was found</li>\n'
              '<li><b>EDSM error</b>– the last transmission status is incorrect</li>\n'
              '</ul>\n'
              '<p>There is currently no additional, separately labeled state “EDSM active” for '
              'EDSM.</p>\n'
              '<p>Inara distinguishes more precisely:</p>\n'
              '<ul>\n'
              '<li><b>INARA out</b>– disabled for the active journal FID</li>\n'
              '<li><b>INARA ready</b>– set up, but still without confirmed transmission in this '
              'session</li>\n'
              '<li><b>INARA transmission</b>– the worker is currently sending</li>\n'
              '<li><b>INARA active</b>– the last actual transfer was successfully confirmed</li>\n'
              '<li><b>INARA error</b>– the last transfer attempt failed</li>\n'
              '</ul>\n'
              '\n'
              '<h3>API-Key security</h3>\n'
              '<p>API-Keys are personal credentials. The input fields are hidden; They are stored '
              'commander-related in the application settings and not in the CMDRHelper '
              'database.</p>\n'
              '<p>Keys should not be published, shared in screenshots, or added to public '
              'repositories.</p>\n'
              '\n'
              '<h3>Images/Screenshots</h3>\n'
              '<p>Source Folder, Destination Folder, PNG/JPG, Auto Processing, BMP Delete, and '
              'Brightening from 0 to 50 percent are located exclusively in the main Images menu, '
              'not on the Settings page.</p>\n'
              '<p>The “Images” context-sensitive help describes these options in detail.</p>\n'
              '\n'
              '<h3>surface</h3>\n'
              '<p>The interface group includes the appearance, language, font, font size, and '
              'value threshold for valuable explorer bodies.</p>\n'
              '\n'
              '<h3>Dark and light mode</h3>\n'
              '<p>You can switch directly between dark and light appearance. The theme is '
              'immediately applied to the interface and existing system and history cards and '
              'saved.</p>\n'
              '\n'
              '<h3>Language</h3>\n'
              '<p>The interface offers twelve languages \u200b\u200bto choose from. “Save '
              'Language” saves the selection; A restart of CMDRHelper is then required for a '
              'completely uniform conversion of existing widgets.</p>\n'
              '\n'
              '<h3>Font and font size</h3>\n'
              '<p>Font family and font size from 7 to 24 pt can be selected and saved.</p>\n'
              '<p>Both changes will only take full effect after a restart. The interface '
              'explicitly indicates this.</p>\n'
              '\n'
              '<h3>Value threshold</h3>\n'
              '<p>The Explorer value threshold determines the estimated credit value from which '
              'bodies are highlighted as particularly valuable. The change is saved immediately '
              'and updates the corresponding Explorer display.</p>\n'
              '\n'
              '<h3>Auto-hide</h3>\n'
              '<p>“Precious Bodies”, “BIO Finds” and “Cargo” are firmly located in the left sidebar, not '
              'within the Settings page.</p>\n'
              '<p>The switches are saved and control the supported small live hint windows during '
              'exploration. The value threshold for Valuable Bodies is set in the interface '
              'settings.</p>\n'
              '<p>The Cargo window exclusively uses the Cargo snapshot confirmed for the active Journal FID. The commander viewed in CMDR View and viewed_commander_id do not affect this live window. For a Ship it shows occupied / maximum · free; if CargoCapacity is unknown, no value is estimated.</p>\n'
              '\n'
              '<h3>Updates</h3>\n'
              '<p>The update group shows installed version and GitHub status. Check Now manually '
              'checks for a new scheduled CMDRHelper version; In addition, a delayed automatic '
              'check takes place after the start.</p>\n'
              '<p>If a new version is available, CMDRHelper will ask before downloading and '
              'installing. An announced database update is shown separately in this dialog.</p>\n'
              '\n'
              '<h3>Download progress</h3>\n'
              '<p>The download runs in the background. If the total size is known, CMDRHelper '
              'shows file name, received and total MiB, percent, transfer rate and estimated '
              'remaining time.</p>\n'
              '<p>Without a known total size, the progress bar works in busy mode and continues to '
              'show the amount of data received and - if determinable - the rate. Before '
              'installation, the downloaded ZIP is checked.</p>\n'
              '\n'
              '<h3>Cancel update</h3>\n'
              '<p>“Cancel download” ends an ongoing download in a controlled manner. An aborted, '
              'incomplete or invalid download will not be installed.</p>\n'
              '\n'
              '<h3>Update on Windows</h3>\n'
              '<p>On Windows, the actual update process continues regardless of the original start '
              'console. A console shutdown should therefore not unintentionally end it.</p>\n'
              '<p>If an error occurs after file changes have begun, the existing rollback backup '
              'attempts to restore the previous version.</p>\n'
              '\n'
              '<h3>Restart after update</h3>\n'
              '<p>After successful installation, the updater CMDRHelper restarts via the intended '
              'start path and briefly checks whether the new process is running stably.</p>\n'
              '<p>If a release requires a one-time database update, the journal archive will also '
              'be reevaluated after the restart.</p>\n'
              '\n'
              '<h3>Several commanders</h3>\n'
              '<p><b>Settings selection = Whose online access am I editing?</b></p>\n'
              '<p><b>Active Journal-FID = Who is allowed to broadcast live?</b></p>\n'
              '<p>Neither the online account selection nor the CMDR view is allowed to switch a '
              'live uploader to a viewed-only commander.</p>\n'
              '\n'
              '<h3>Help</h3>\n'
              '<p>"? Help" is located in the left sidebar above "auto show" and opens the help of '
              'the currently visible main menu area.</p>\n'
              '<p>In the “Settings” area, the button opens this settings help directly.</p>\n'
              '\n'
              '<h3>Tip</h3>\n'
              '<p>If you are reinstalling or have problems, check first:</p>\n'
              '<ul>\n'
              '<li>correct journal folder and recognized commander identity</li>\n'
              '<li>desired language, theme, font and explorer value threshold</li>\n'
              '<li>Online access to the correct FID</li>\n'
              '<li>In case of image problems, source and target folders in the “Images” main '
              'menu</li>\n'
              '</ul>\n'
              '<p>If there are several commanders, always pay attention to which FID the visible '
              'online access data applies to.</p>')}

DIALOG_TITLE = 'Help – {area}'
CLOSE_LABEL = 'Close'
