"""Norwegian content for contextual help."""


HELP_TOPICS = {'overview': ('Oversikt',
              '<h2>Oversikt</h2>\n'
              '<p>Oversikten er hjemmesiden til CMDRHelper. Den oppsummerer den viktigste '
              'informasjonen om den aktive fartøysjefen og viser med et blikk om journalen, '
              'lokasjonen og nettjenestene er korrekt gjenkjent.</p>\n'
              '\n'
              '<h3>Kommandør og skip</h3>\n'
              '<p>Fartøysjefen gjenkjent fra Elite Dangerous Journal og skipet som er i bruk vises '
              'her.</p>\n'
              '<p>CMDRHelper tildeler personlige data til den respektive fartøysjefen basert på '
              'Frontier ID (FID). Dette holder data fra forskjellige sjefer atskilt fra '
              'hverandre.</p>\n'
              '<p>Ved endring av fartøysjefen lastes den lagrede informasjonen knyttet til den nye '
              'fartøysjefen.</p>\n'
              '\n'
              '<h3>tidsskrift</h3>\n'
              '<p>CMDRHelper bruker Elite Dangerous sine journalfiler som sin hoveddatakilde.</p>\n'
              '<p>Journalvisningen informerer om journalfiler er funnet og tildelt den aktive '
              'sjefen. Nye komplette journaloppføringer blir automatisk behandlet under '
              'spilling.</p>\n'
              '<p>Journalområder som allerede er behandlet lagres slik at CMDRHelper ikke trenger '
              'å fullstendig evaluere hver journal på nytt neste gang den startes.</p>\n'
              '\n'
              '<h3>Gjeldende plassering</h3>\n'
              '<p>Viser det for øyeblikket kjente stjernesystemet og - så vidt kjent fra journalen '
              '- eksakt plassering av fartøysjefen.</p>\n'
              '<p>Plasseringen oppdateres av hendelser som hopp, dokking og andre '
              'posisjonsrapporter og lagres på kommando-for-kommando-basis.</p>\n'
              '\n'
              '<h3>Oppdrag</h3>\n'
              '<p>Dette området viser antall kjente åpne oppdrag.</p>\n'
              '<p>"Oppdrag"-knappen eller menyelementet tar deg til hele oppdragsvisningen med '
              'kjente oppdragsmål og statusinformasjon.</p>\n'
              '\n'
              '<h3>Siste stand</h3>\n'
              '<p>"Siste tilstand" oppsummerer den siste kjente vedvarende sjefstilstanden. Dette '
              'gjør at viktig informasjon kan gjenopprettes selv etter omstart av Elite Dangerous '
              'eller CMDRHelper.</p>\n'
              '\n'
              '<h3>Endelige systemer</h3>\n'
              '<p>Systemer som nylig er besøkt eller gjenkjent fra journalen, vises her.</p>\n'
              '<p>Listen fungerer som en rask oversikt over fartøysjefens siste reise.</p>\n'
              '\n'
              '<h3>Online status</h3>\n'
              '<p>Det er flere statusindikatorer øverst i hovedvinduet:</p>\n'
              '<ul>\n'
              '<li><b>Journal anerkjent</b>– CMDRHelper oppdaget en gyldig journalkilde og '
              'sjefsidentitet.</li>\n'
              '<li><b>EDSM</b>– viser gjeldende status for EDSM-overføringen for den aktive '
              'journalen FID.</li>\n'
              '<li><b>INARA</b>– viser gjeldende status for Inara-overføringen for den aktive '
              'journalen FID.</li>\n'
              '</ul>\n'
              '<p>Online tilgangsdata administreres separat for hver sjef. En fartøysjef bruker '
              'aldri automatisk en annen farmands API-Key.</p>\n'
              '\n'
              '<h3>Viktig for flere befal</h3>\n'
              '<p>Live-dataene avhenger alltid av fartøysjefen som ble tydelig identifisert av den '
              'gjeldende Elite Dangerous-journaløkten.</p>\n'
              '<p>Bare å vise en annen kommando i en visning endrer ikke den aktive '
              'direktekommandøren eller påvirker noen EDSM- eller Inara-sendinger.</p>\n'
              '\n'
              '<h3>Tupp</h3>\n'
              '<p>Hvis fartøysjefen, skipet eller plasseringen ikke samsvarer med gjeldende status '
              'i spillet, sjekk først journalvisningen øverst og sjekk deretter journalmappen satt '
              'under "Innstillinger".</p>'),
 'missions': ('Oppdrag',
              '<h2>Oppdrag</h2>\n'
              '<p>Oppdragsvisningen viser oppdragene til den nåværende sjefen som er kjent fra '
              'Elite Dangerous Journal. CMDRHelper lagrer oppdragsdata på '
              'kommando-for-kommando-basis, slik at åpne oppdrag beholdes selv etter en omstart av '
              'Elite Dangerous eller CMDRHelper.</p>\n'
              '\n'
              '<h3>Åpne oppdrag</h3>\n'
              '<p>Nye oppdrag kommer ut<code>MissionAccepted</code>overtatt og lagret '
              'permanent.</p>\n'
              '<p>Så lenge det ikke er noen endelig oppdragshendelse, forblir oppdraget åpent. En '
              'ny spilløkt uten oppdragsliste vil kanskje ikke automatisk fjerne kjente åpne '
              'oppdrag.</p>\n'
              '\n'
              '<h3>Oppdragsstatus</h3>\n'
              '<p>CMDRHelper behandler blant annet følgende statusendringer:</p>\n'
              '<ul>\n'
              '<li>Oppdrag akseptert</li>\n'
              '<li>Oppdraget fullført</li>\n'
              '<li>Oppdraget mislyktes</li>\n'
              '<li>Oppdraget ble avbrutt</li>\n'
              '<li>Oppdragsmålet omdirigert</li>\n'
              '<li>Fremgang på støttede last-/depotoppdrag</li>\n'
              '</ul>\n'
              '<p>En siste hendelse endrer bare det tilknyttede oppdraget.</p>\n'
              '\n'
              '<h3>Oppdrag fra tidsskriftet</h3>\n'
              '<p>Elite Dangerous gir oppdragsinformasjon om ulike journalbegivenheter. CMDRHelper '
              'slår sammen disse hendelsene til en vedvarende oppdragstilstand.</p>\n'
              '<p>En ekte oppdragsbegivenhet kan tjene som et autoritativt øyeblikksbilde. Hvis et '
              'slikt arrangement mangler, vil ikke eldre åpne oppdrag bli stengt bare av denne '
              'grunn.</p>\n'
              '\n'
              '<h3>Destinasjoner og steder</h3>\n'
              '<p>I den grad Elite gir informasjonen i journalen, viser CMDRHelper:</p>\n'
              '<ul>\n'
              '<li>Målsystem</li>\n'
              '<li>Destinasjonsstasjon eller destinasjon</li>\n'
              '<li>Målplanet eller kropp</li>\n'
              '<li>Oppdragsbetegnelse</li>\n'
              '<li>kjent fremgang</li>\n'
              '<li>nåværende status</li>\n'
              '</ul>\n'
              '<p>Ikke alle oppdrag gir all informasjon. Manglende data er ikke oppfunnet av '
              'CMDRHelper.</p>\n'
              '\n'
              '<h3>Utholdenhet og start på nytt</h3>\n'
              '<p>Åpne oppdrag lagres i den sjefsrelaterte databasen.</p>\n'
              '<p>Dette betyr at de beholdes selv om:</p>\n'
              '<ul>\n'
              '<li>Elite Dangerous avsluttes og startes på nytt senere</li>\n'
              '<li>CMDRHelper er stengt i mellom</li>\n'
              '<li>Den nye journaløkten inneholder i utgangspunktet ingen misjonshendelser</li>\n'
              '</ul>\n'
              '<p>Bare en dokumentert oppdragshendelse endrer den lagrede tilstanden.</p>\n'
              '\n'
              '<h3>Flere befal</h3>\n'
              '<p>Oppdragene er strengt adskilt av sjefen.</p>\n'
              '<p>En oppdragshendelse er kun tildelt sjefen hvis journaløkt er unikt identifisert. '
              'Oppdrag fra en annen sjef kan ikke vises eller endres.</p>\n'
              '\n'
              '<h3>Foreldreløse eller ikke lenger gyldige oppdrag</h3>\n'
              '<p>Hvis eldre journaldata eller en tidligere import holder et oppdrag åpent selv om '
              'det ikke lenger eksisterer i spillet, kan den eksisterende funksjonen for '
              'tilbakestilling/opprydding av foreldreløse oppdrag brukes.</p>\n'
              '<p>Denne funksjonen skal bare brukes hvis det er tydelig at det viste oppdraget '
              'ikke lenger er aktivt.</p>\n'
              '\n'
              '<h3>Online tjenester</h3>\n'
              '<p>Støttede oppdragshendelser kan i tillegg overføres til Inara hvis en gyldig og '
              'aktivert Inara-tilgang er satt opp for den aktive journalen FID.</p>\n'
              '<p>En manglende eller utilgjengelig Inara-tilkobling påvirker ikke lokal '
              'oppdragslagring.</p>\n'
              '\n'
              '<h3>Tupp</h3>\n'
              '<p>Hvis et oppdrag ikke vises eller viser en feil status, sjekk først om Elite '
              'Dangerous allerede har skrevet den tilsvarende oppdragshendelsen til '
              'journalen.</p>\n'
              '<p>CMDRHelper kan bare vise informasjon som journalen faktisk gir eller som '
              'allerede er lagret fra tidligere unike oppdragsbegivenheter.</p>'),
 'explorer': ('Utforsker',
              '<h2>Utforsker</h2>\n'
              '<p>Utforskeren evaluerer systemene og himmellegemene oppdaget og skannet av den '
              'aktive sjefen. Den kombinerer dine egne Elite Dangerous-journaldata med allerede '
              'tilgjengelig tilleggsinformasjon og viser utforskning, kartografi, '
              'biologiske/geologiske signaler og overflategruvedata sammen.</p>\n'
              '\n'
              '<h3>Nåværende system</h3>\n'
              '<p>Det nåværende kunnskapsnivået om systemet er oppsummert i det øvre området.</p>\n'
              '<p>Disse inkluderer blant annet:</p>\n'
              '<ul>\n'
              '<li>kjente og til og med registrerte kropper i journalen</li>\n'
              '<li>eksisterende signaler</li>\n'
              '<li>Skann verdier</li>\n'
              '<li>kartografiverdi allerede oppnådd</li>\n'
              '<li>mulig totalverdi hvis fullstendig kartlagt</li>\n'
              '<li>BIO-status og estimerte BIO-verdier</li>\n'
              '<li>Kartografi og BIO-data som ennå ikke er sendt inn</li>\n'
              '</ul>\n'
              '<p>Verdiene som vises er basert på faktisk tilgjengelige data. Manglende '
              'informasjon presenteres ikke som et eget funn.</p>\n'
              '\n'
              '<h3>Systemkart</h3>\n'
              '<p>Systemkartet representerer grafisk stjerner, planeter, måner og andre kjente '
              'kropper i det nåværende systemet.</p>\n'
              '<p>En kropp kan klikkes for å åpne dens detaljerte visning.</p>\n'
              '<p>Displayet viser blant annet kroppstype, avstand og – hvis tilgjengelig – '
              'skannings- og kartografiverdier samt spesielle leteegenskaper.</p>\n'
              '\n'
              '<h3>ØKOLOGISK ×N</h3>\n'
              '<p>BIO ×N angir antall biologiske signaler fra en kropp som er rapportert av '
              'spillet.</p>\n'
              '<p>Tallet indikerer i utgangspunktet bare hvor mange biologiske signaler eller '
              'slekter som ble rapportert. Det betyr ikke automatisk at alle biologiske arter '
              'allerede er funnet eller analysert.</p>\n'
              '<p>Faktiske egne organiske funn holdes separat.</p>\n'
              '\n'
              '<h3>GEO ×N</h3>\n'
              '<p>GEO ×N viser antall geologiske signaler til en kropp rapportert av spillet.</p>\n'
              '<p>Disse kan for eksempel inkludere geologiske trekk som fumaroler eller geysirer. '
              'CMDRHelper viser kun informasjonen som fremkommer fra eksisterende '
              'journal/kroppsdata.</p>\n'
              '\n'
              '<h3>ABBAU ×N</h3>\n'
              '<p>ABBAU ×N viser antall planetariske gruveplasser for en kropp rapportert av Elite '
              'Dangerous.</p>\n'
              '<p>Eksempel:</p>\n'
              '<p><b>ABBAU ×24</b></p>\n'
              '<p>betyr at 24 planetariske gruveplasser er rapportert for denne kroppen.</p>\n'
              '<p>Tallet sier ikke hvilket råstoff som kan utvinnes på et enkelt sted.</p>\n'
              '\n'
              '<h3>Egne gruvefunn</h3>\n'
              '<p>Hvis fartøysjefen faktisk har utført overflategruvedrift med Rhino, lagrer '
              'CMDRHelper de personlige funnene som er dokumentert separat.</p>\n'
              '<p>Det skilles mellom:</p>\n'
              '<ul>\n'
              '<li>faktisk innhentede varer, f.eks. B. Kobber i tonn</li>\n'
              '<li>sekundære materialer samlet under gruvedrift</li>\n'
              '<li>generelle overflatematerialer av kroppen</li>\n'
              '</ul>\n'
              '<p>Et eksempel på et personlig funn kan være:</p>\n'
              '<p><b>Kobber – 56 t</b></p>\n'
              '<p>Denne informasjonen betyr at denne fartøysjefen faktisk hentet ut 56 tonn kobber '
              'der.</p>\n'
              '<p>De personlige gruvefunnene lagres for hver befal og blandes ikke med funnene til '
              'andre befal.</p>\n'
              '\n'
              '<h3>Materialer på kroppsoverflaten</h3>\n'
              '<p><code>Scan.Materials</code>beskriver den generelle '
              'overflatematerialsammensetningen til en kropp.</p>\n'
              '<p>For eksempel kan jern, nikkel, svovel eller andre materialer vises med '
              'prosentverdier.</p>\n'
              '<p>Disse verdiene bør ikke forveksles med råvarene til et planetarisk gruvedepot. '
              'Frontier gir ingen dokumentert direkte assosiasjon mellom disse generelle '
              'kroppsmaterialene og innholdet på et individuelt gruvested i Journal.</p>\n'
              '\n'
              '<h3>Terraforming</h3>\n'
              '<p>Symbolet eller etiketten for terraforming viser at en kropp anses som en '
              'terraforming-kandidat basert på tilgjengelige data.</p>\n'
              '\n'
              '<h3>Første oppdagelse</h3>\n'
              '<p>Den første funnindikatoren identifiserer kropper for hvilke, i henhold til '
              'tilgjengelige data, et første funn er mulig eller har blitt dokumentert tilsvarende '
              'av kroppens egen journal.</p>\n'
              '<p>Den endelige vurderingen er basert på forholdene rapportert av Elite Dangerous '
              'eller tilgjengelige data.</p>\n'
              '\n'
              '<h3>Første kartlegging</h3>\n'
              '<p>CMDRHelper skiller mellom:</p>\n'
              '<ul>\n'
              '<li>Første kartlegging kan være tilgjengelig</li>\n'
              '<li>kartlagt av fartøysjefen</li>\n'
              '<li>Første kartlegging hevdet av fartøysjefen</li>\n'
              '</ul>\n'
              '<p>Dette gjør det mulig å se om en kropp allerede er kartlagt og om fartøysjefen '
              'din krever førstekartstatus.</p>\n'
              '\n'
              '<h3>Country bar</h3>\n'
              '<p>Landbarhetsindikatoren identifiserer kropper som, ifølge kjente data, er mulig å '
              'lande på.</p>\n'
              '\n'
              '<h3>Gullrammer / verdifulle kropper</h3>\n'
              '<p>Spesielt verdifulle kropper kan fremheves i utforskerdisplayet.</p>\n'
              '<p>Gullrammen fungerer som en rask visuell orientering for kropper over '
              'verditerskelen gitt i CMDRHelper.</p>\n'
              '<p>Den erstatter ikke den detaljerte visningen av kroppens verdi.</p>\n'
              '\n'
              '<h3>Liste over verdier</h3>\n'
              '<p>Verdilisten gir en mer kompakt oversikt over kjente kropper og deres '
              'utforsknings-/kartografiverdier.</p>\n'
              '<p>Den er spesielt egnet for raskt å sammenligne interessante eller verdifulle '
              'kropper i et system.</p>\n'
              '\n'
              '<h3>ØKOLOGISK / GEO / DEGRADERING</h3>\n'
              '<p>Dette synet grupperer kropper med biologiske, geologiske eller planetariske '
              'nedbrytningssignaler.</p>\n'
              '<p>Dette betyr at interessante kropper ikke trenger å søkes opp individuelt i det '
              'komplette systemkartet.</p>\n'
              '<p>Hvis du har dine egne gruvedata på overflaten, kan dine personlige gruvefunn '
              'også være synlige.</p>\n'
              '\n'
              '<h3>Kroppsdetalj</h3>\n'
              '<p>Ved å klikke på en kropp åpnes den detaljerte visningen.</p>\n'
              '<p>Så vidt kjent kan følgende vises der:</p>\n'
              '<ul>\n'
              '<li>Kroppstype</li>\n'
              '<li>masse</li>\n'
              '<li>avstand</li>\n'
              '<li>Tyngdekraften</li>\n'
              '<li>atmosfære</li>\n'
              '<li>Landbarhet</li>\n'
              '<li>Terraforming status</li>\n'
              '<li>BIO/GEO-signaler</li>\n'
              '<li>planetariske gruveplasser</li>\n'
              '<li>Overflatematerialer</li>\n'
              '<li>egne gruvefunn</li>\n'
              '<li>Skanneverdi</li>\n'
              '<li>kartografiverdi</li>\n'
              '<li>nåværende verdi</li>\n'
              '</ul>\n'
              '<p>Ikke alle organer har all informasjonen.</p>\n'
              '\n'
              '<h3>BIO-prognoser</h3>\n'
              '<p>CMDRHelper kan estimere mulige biologiske funn basert på eksisterende data om '
              'egnede kropper.</p>\n'
              '<p>Spådommer er ikke en garanti for at en bestemt art faktisk vil være til stede. '
              'De tjener som beslutningshjelp for leting.</p>\n'
              '<p>Estimerte BIO-verdier er også spådommer og behandles separat fra faktiske '
              'bekreftede funn.</p>\n'
              '\n'
              '<h3>Ikke sendt inn ennå</h3>\n'
              '<p>CMDRHelper vedlikeholder sjefsrelaterte kjente kartografi- og BIO-data som ennå '
              'ikke er sendt inn.</p>\n'
              '<p>Kartografisalg og biologiske royalties regnskapsføres ved å bruke de tilsvarende '
              'journalhendelsene.</p>\n'
              '<p>Kartografidata som allerede er solgt skal ikke vises som åpne igjen etter '
              'rekonstruksjon.</p>\n'
              '\n'
              '<h3>Vis bil</h3>\n'
              '<p>Støttede Explorer-tips som verdifulle kropper eller BIO-funn kan vises '
              'automatisk ved hjelp av bryterne i venstre sidefelt.</p>\n'
              '<p>Disse små live-vinduene fungerer som ekstra hint mens du spiller og erstatter '
              'ikke hele Explorer-visningen.</p>\n'
              '\n'
              '<h3>Flere befal</h3>\n'
              '<p>Personlige leteresultater, kartografi, BIO-funn og egne gruvefunn på overflaten '
              'tildeles den respektive sjefen.</p>\n'
              '<p>Globale astronomiske egenskaper til en kropp - for eksempel antallet kjente '
              'planetariske gruveplasser - forblir egenskapene til kroppen selv.</p>\n'
              '\n'
              '<h3>Tupp</h3>\n'
              '<p>Hvis du har en interessant kropp, er det verdt å klikke på den detaljerte '
              'visningen. Dette er det beste stedet å skille mellom generelle kroppsdata, mulige '
              'leteresultater og faktiske funn dokumentert av din egen sjef.</p>'),
 'chronicle': ('kronikk',
               '<h2>kronikk</h2>\n'
               '<p>Kronikken er fartøysjefens personlige reise- og oppdagelseshistorie. Den bruker '
               'den permanent lagrede journalinformasjonen til å finne systemer som allerede er '
               'besøkt, for å representere dem romlig og for å søke etter kjente funn.</p>\n'
               '\n'
               '<h3>Systemer besøkt</h3>\n'
               '<p>Krøniken viser systemene som ble besøkt og deres plassering i galaksen '
               'kjent for kommandøren.</p>\n'
               '<p>Hvis tilgjengelig, tas det hensyn til første og siste besøk samt kjent '
               'kroppsinformasjon.</p>\n'
               '<p>Kronikken er derfor ikke bare et kart, men også et verktøy for å finne '
               'tidligere reisemål og oppdagelser.</p>\n'
               '\n'
               '<h3>3D kart</h3>\n'
               '<p>Systemene som besøkes er romlig representert ved hjelp av deres galaktiske '
               'X/Y/Z-koordinater.</p>\n'
               '<p>Bruksanvisningen er plassert rett over kartet:</p>\n'
               '<ul>\n'
               '<li>Hold nede venstre museknapp → roter visning</li>\n'
               '<li>Hold nede den midterste museknappen → Zoom</li>\n'
               '<li>Hold nede høyre museknapp → flytt visning</li>\n'
               '</ul>\n'
               '<p>Displayet med liten akse hjelper med orientering i rommet.</p>\n'
               '\n'
               '<h3>Nåværende stilling</h3>\n'
               '<p>Med "Current Position" kan kartvisningen justeres eller returneres til den '
               'gjeldende kjente plasseringen til den aktive fartøysjefen.</p>\n'
               '<p>Forutsetningen er at en gyldig aktuell stilling er kjent for fartøysjefen.</p>\n'
               '\n'
               '<h3>Juster</h3>\n'
               '<p>"Align" returnerer kartorienteringen til den tiltenkte grunnleggende '
               'orienteringen.</p>\n'
               '<p>Dette er nyttig hvis kartet har blitt forvirrende etter å ha blitt rotert eller '
               'flyttet mye.</p>\n'
               '\n'
               '<h3>Oppdater tidslinjen</h3>\n'
               '<p>"Oppdater historikk" oppdaterer skjermen med gjeldende kjente data.</p>\n'
               '<p>Funksjonen endrer ikke journalfiler eller oppretter nye letedata. Den '
               'oppdaterer ganske enkelt historievisningen basert på eksisterende '
               'CMDRHelper-data.</p>\n'
               '\n'
               '<h3>Fritekstsøk</h3>\n'
               '<p>Allerede kjent innhold kan søkes i feltet "Søkehistorikk...".</p>\n'
               '<p>Søket tar blant annet hensyn til – hvis tilgjengelig i databasen –:</p>\n'
               '<ul>\n'
               '<li>Systemnavn</li>\n'
               '<li>Kroppsegenskaper</li>\n'
               '<li>biologiske data</li>\n'
               '<li>Materialer</li>\n'
               '<li>Codex data</li>\n'
               '</ul>\n'
               '<p>"Søk"-knappen utfører kun dette fritekstsøket.</p>\n'
               '<p>De separate DEMONTERING-filtrene utføres derimot med "Apply".</p>\n'
               '\n'
               '<h3>Søkeresultater</h3>\n'
               '<p>Treff vises i den eksisterende resultatlisten under kronikkkortet.</p>\n'
               '<p>Avhengig av type treff, kan system og kropp samt tilleggsinformasjon '
               'vises.</p>\n'
               '<p>Et treff kan brukes til å finne det korresponderende systemet eller kroppen som '
               'allerede er kjent og for å åpne den eksisterende detaljerte informasjonen.</p>\n'
               '\n'
               '<h3>Planetariske gruveplasser</h3>\n'
               '<p>Filteret "Planetære gruvesteder" kan brukes til å spesifikt søke etter kjente '
               'kropper som Elite Dangerous har rapportert planetariske gruvesteder for.</p>\n'
               '<p>Den underliggende skjermen tilsvarer den kjent fra Explorer:</p>\n'
               '<p><b>ABBAU ×N</b></p>\n'
               '<p>Nummeret tilhører selve kroppen og er ikke relatert til fartøysjefen.</p>\n'
               '\n'
               '<h3>I det minste</h3>\n'
               '<p>Ved å bruke "Minst" kan du spesifisere minimumsantallet av planetariske '
               'gruveplasseringer en kropp skal ha.</p>\n'
               '<p>Eksempel:</p>\n'
               '<p><b>Minst 20</b></p>\n'
               '<p>viser kun kjente kropper med minst:</p>\n'
               '<p><b>ABBAU ×20</b></p>\n'
               '<p>Dette gjør det mulig å spesifikt lokalisere spesielt omfattende '
               'gruveområder.</p>\n'
               '\n'
               '<h3>Egne gruvefunn</h3>\n'
               '<p>Med «Egne gruvefunn» er letinga avgrensa til kroppar der den aktuelle '
               'farandsjefen påviselig sjølv har utført gruvedrift.</p>\n'
               '<p>Denne informasjonen kommer fra personlig overflategruvehistorie og er strengt '
               'adskilt av sjefen.</p>\n'
               '<p>Et organ kan derfor ha globale ABBAU ×N-signaler uten at egen sjef allerede har '
               'fjernet noe der.</p>\n'
               '\n'
               '<h3>råstoff</h3>\n'
               '<p>Hvis "Egne gruvefunn" er aktivert, er valget "Råmateriale" også '
               'tilgjengelig.</p>\n'
               '<p>Listen inneholder kun varer som den aktuelle fartøysjefen faktisk allerede har '
               'vunnet fra overflategruvedrift.</p>\n'
               '<p>Dette er ikke en teoretisk liste over alle mulige gruve råvarer.</p>\n'
               '<p>For eksempel kan FABER38 vises:</p>\n'
               '<ul>\n'
               '<li>Alle</li>\n'
               '<li>kopper</li>\n'
               '</ul>\n'
               '<p>Hvis ytterligere råvarer faktisk utvinnes senere, vil de automatisk vises i '
               'ditt personlige valg.</p>\n'
               '\n'
               '<h3>Målrettet søk etter råvarer</h3>\n'
               '<p>For eksempel, hvis "Kobber" er valgt og deretter "Bruk" trykkes, vil '
               'historikken kun vise kropper som den aktuelle fartøysjefen beviselig har utvunnet '
               'kobber på.</p>\n'
               '<p>Eksempel:</p>\n'
               '<p><b>Prua Hypai NV-E c28-66 / 2 — ABBAU ×24 — kobber 56 t</b></p>\n'
               '<p>Dette betyr at kronikken kan brukes som en personlig lokasjonsdatabase: et '
               'råmateriale som allerede er utvunnet kan bli funnet igjen senere.</p>\n'
               '\n'
               '<h3>Alle råvarer</h3>\n'
               '<p>Med "Råmateriale: Alle" blir alle matchende personlige gruvefunn på overflaten '
               'tatt i betraktning.</p>\n'
               '<p>Hvis flere varer er kjent på en kropp, kan de vises sammen med mengdene de har '
               'fått til nå.</p>\n'
               '<p>Eksempel:</p>\n'
               '<p><b>ABBAU ×24 — Helium-3 18 t, kobber 56 t</b></p>\n'
               '<p>Mengdene er de personlige gruveverdiene til den respektive sjefen, som faktisk '
               'er dokumentert fra journalhendelser.</p>\n'
               '\n'
               '<h3>Kombiner filtre</h3>\n'
               '<p>Gruvefiltrene kan kombineres med hverandre.</p>\n'
               '<p>For eksempel:</p>\n'
               '<ul>\n'
               '<li>Planetariske gruveplasser er aktive</li>\n'
               '<li>Minst 20</li>\n'
               '<li>Egne gruvefunn aktive</li>\n'
               '<li>Råstoff kobber</li>\n'
               '</ul>\n'
               '<p>leter etter kjente kropper med minst 20 planetariske gruveplasser der '
               'vedkommende fartøysjef allerede selv har utvunnet kobber.</p>\n'
               '\n'
               '<h3>Søke</h3>\n'
               '<p>"Apply" kjører bare de synlige gruvefiltrene.</p>\n'
               '<p>"Søk"-knappen ved siden av den er reservert for fritekstsøk.</p>\n'
               '<p>Dette betyr at tekstsøk og gruvefiltre er bevisst atskilt fra hverandre.</p>\n'
               '\n'
               '<h3>Tilbakestill</h3>\n'
               '<p>"Tilbakestill" sletter gjeldende fritekstsøk og tilbakestiller også '
               'gruvefiltrene til deres opprinnelige tilstand.</p>\n'
               '<p>Råvareutvalget hopper tilbake til "Alle".</p>\n'
               '\n'
               '<h3>Kommandørvalg</h3>\n'
               '<p>Kronikken kan vise data fra ulike kjente befal.</p>\n'
               '<p>Personlig informasjon som dine egne gruvefunn og råvarelister blir imidlertid '
               'alltid vurdert separat for fartøysjefen som faktisk vises.</p>\n'
               '<p>En fartøysjef ser ingen gruvefunn i sitt råvareutvalg som utelukkende tilhører '
               'en annen fartøysjef.</p>\n'
               '\n'
               '<h3>Alle befal</h3>\n'
               '<p>Kart-/kronikkvisningen kan ta hensyn til flere kommandoer.</p>\n'
               '<p>Dette endrer ikke den personlige tilordningen av befalsrelaterte data. Globale '
               'astronomiske egenskaper til et system eller kropp forblir delt, personlige funn '
               'forblir atskilt.</p>\n'
               '\n'
               '<h3>Søkehjelp / legende</h3>\n'
               '<p>Ytterligere informasjon om kronikksøket og betydningen av displayet kan nås via '
               '"Søkehjelp / legende".</p>\n'
               '<p>Denne kontekstrelaterte hovedhjelpen supplerer den korte bruksanvisningen som '
               'er tilgjengelig der.</p>\n'
               '\n'
               '<h3>Tupp</h3>\n'
               '<p>Kronikken egner seg spesielt godt til å finne interessante steder som ble '
               'oppdaget under en lengre tur.</p>\n'
               '<p>For overflategruvedrift, for eksempel, kan den svare:</p>\n'
               '<p>"På hvilken planet har jeg noen gang utvunnet kobber?"</p>\n'
               '<p>eller:</p>\n'
               '<p>"Hvilke av mine kjente planeter har et spesielt høyt antall gruveplasser?"</p>'),
 'jump_tip': ('Hopptips',
              '<h2>Hopptips</h2>\n'
              '<p>Hopptipset støtter utforskning ved å evaluere allerede kjente systemdata og '
              'fremheve interessante målsystemer.</p>\n'
              '<p>Funksjonen er ment som et beslutningshjelpemiddel. Det garanterer ikke at et '
              'anbefalt system faktisk inneholder sjeldne eller spesielt verdifulle funn.</p>\n'
              '\n'
              '<h3>Grunnlag for evalueringen</h3>\n'
              '<p>CMDRHelper bruker eksisterende journal- og databaseinformasjon for å evaluere '
              'kjente mønstre i systemnavn og systemklasser.</p>\n'
              '<p>Det kan blant annet tas hensyn til systemforkortelser, allerede kjente '
              'kroppstyper og tidligere funn.</p>\n'
              '\n'
              '<h3>Systemforkortelse</h3>\n'
              '<p>Mange prosedyregenererte systemer i Elite Dangerous inneholder bokstav- og '
              'tallkombinasjoner som identifiserer spesifikke systemgrupper.</p>\n'
              '<p>CMDRHelper kan statistisk evaluere disse forkortelsene og vise i hvilke grupper '
              'interessante funn forekom hyppigere i dataene som er kjent til dags dato.</p>\n'
              '\n'
              '<h3>Revurdere</h3>\n'
              '<p>Med "Re-evaluate" analyseres den eksisterende databasen på nytt.</p>\n'
              '<p>Fartøysjefens lagrede data brukes. Funksjonen oppretter ikke nye elitedata eller '
              'endrer journalfiler.</p>\n'
              '\n'
              '<h3>Resultatliste</h3>\n'
              '<p>Resultatlisten viser de mest interessante systemforkortelsene eller kandidatene '
              'i henhold til den aktuelle evalueringen.</p>\n'
              '<p>Avhengig av eksisterende database kan det være informasjon om:</p>\n'
              '<ul>\n'
              '<li>interessante planetariske klasser</li>\n'
              '<li>biologiske funn</li>\n'
              '<li>Vannverdener</li>\n'
              '<li>terraformerbare kropper</li>\n'
              '<li>andre bemerkelsesverdige leteresultater</li>\n'
              '</ul>\n'
              '<p>vises.</p>\n'
              '\n'
              '<h3>Sannsynlighet i stedet for garanti</h3>\n'
              '<p>En høy verdi eller en god rangering betyr bare at et bestemt mønster oftere ble '
              'assosiert med interessante funn i dataene som er evaluert så langt.</p>\n'
              '<p>Det er ingen garanti.</p>\n'
              '<p>Et anbefalt system kan fortsatt være helt uinteressant, mens et lavt vurdert '
              'system kan inneholde verdifulle funn.</p>\n'
              '\n'
              '<h3>Egen database</h3>\n'
              '<p>Hopptipset fungerer med fartøysjefens allerede kjente data.</p>\n'
              '<p>Jo flere systemer og organer som registreres over tid, desto større blir den '
              'personlige databasen for evaluering.</p>\n'
              '<p>Dette betyr at rangeringen kan endres senere.</p>\n'
              '\n'
              '<h3>Flere befal</h3>\n'
              '<p>Personlige evalueringer håndteres på kommando-for-kommando basis.</p>\n'
              '<p>Data fra en annen fartøysjef må ikke forfalske den personlige vurderingen '
              'ubemerket.</p>\n'
              '<p>Globale astronomiske masterdata kan derimot deles så lenge de ikke representerer '
              'befalsrelaterte personlige funn.</p>\n'
              '\n'
              '<h3>Bruk i praksis</h3>\n'
              '<p>Hopptipset egner seg spesielt hvis det er flere mulige destinasjoner å velge '
              'mellom og det ønskes ytterligere beslutningshjelp.</p>\n'
              '<p>Den erstatter ikke en komplett ruteplanlegger og beregner ikke en sikker, '
              'optimal rute.</p>\n'
              '<p>Menypunktet "Ruteplanlegger" er tilgjengelig for spesifikk ruteplanlegging.</p>\n'
              '\n'
              '<h3>Tupp</h3>\n'
              '<p>Bruk hopptipset som en ekstra letehjelp:</p>\n'
              '<p>"I følge mine tidligere data, hvilket system virker mer interessant?"</p>\n'
              '<p>Ikke som en spådom:</p>\n'
              '<p>"Det er garantert et spesifikt funn i dette systemet."</p>'),
 'route_planner': ('Ruteplanlegger',
                   '<h2>Ruteplanlegger</h2>\n'
                   '<p>Ruteplanleggeren støtter planlegging av lengre turer med skip eller Fleet '
                   'Carrier. CMDRHelper kan bruke eksterne rutedata fra Spansh og forberede den '
                   'planlagte ruten for videre bruk.</p>\n'
                   '\n'
                   '<h3>Start og slutt</h3>\n'
                   '<p>Et start- og målsystem kreves for ruteberegning.</p>\n'
                   '<p>I den grad det er mulig kan CMDRHelper bruke fartøysjefens gjeldende kjente '
                   'system som utgangspunkt. Start og mål bør kontrolleres før beregning.</p>\n'
                   '\n'
                   '<h3>Send eller Fleet Carrier</h3>\n'
                   '<p>Ruteplanleggeren skiller mellom turer med et vanlig skip og med en Fleet '
                   'Carrier.</p>\n'
                   '<p>Begge bruker ulike krav og beregningsmetoder. Derfor må riktig rutetype '
                   'velges før planlegging.</p>\n'
                   '\n'
                   '<h3>Skipsrute</h3>\n'
                   '<p>For en skipsrute er det tatt hensyn til hoppegenskapene som er kjent eller '
                   'lagt inn for det aktive skipet.</p>\n'
                   '<p>Avhengig av tilgjengelige data kan FSD-data, skipsdata, masse, drivstoff og '
                   'andre hoppparametere inkluderes i planleggingen.</p>\n'
                   '<p>En beregnet rute er et planleggingshjelpemiddel. Endringer i skipet eller '
                   'dets masse kan endre den faktiske hoppedistansen som er oppnåelig i '
                   'spillet.</p>\n'
                   '\n'
                   '<h3>Flåtetransportrute</h3>\n'
                   '<p>Fleet Carrier har andre hoppregler enn vanlige skip.</p>\n'
                   '<p>CMDRHelper bruker den utpekte Spansh transportørplanleggingen for '
                   'tilsvarende ruter.</p>\n'
                   '<p>Ruten brukes til å planlegge hoppsekvensen. Faktisk tritiumforbruk og '
                   'tilgjengelig rekkevidde kan også avhenge av masse og gjeldende '
                   'transportørstatus.</p>\n'
                   '\n'
                   '<h3>Spansh</h3>\n'
                   '<p>For selve ruteberegningen kan CMDRHelper bruke den eksterne tjenesten '
                   'Spansh.</p>\n'
                   '<p>Forespørselen behandles i bakgrunnen slik at grensesnittet forblir '
                   'operativt under en lengre beregning.</p>\n'
                   '<p>CMDRHelper har ingen innflytelse på tilgjengeligheten eller responstiden '
                   'til den eksterne tjenesten.</p>\n'
                   '\n'
                   '<h3>beregning</h3>\n'
                   '<p>Etter å ha startet en beregning, sendes forespørselen videre til den valgte '
                   'ruteplanleggeren.</p>\n'
                   '<p>Avhengig av ruten og tjenesten, kan beregningen ta litt tid. I løpet av '
                   'denne tiden skal ingen andre identiske beregninger startes unødvendig.</p>\n'
                   '\n'
                   '<h3>Resultat</h3>\n'
                   '<p>En vellykket beregnet rute viser de tiltenkte systemene eller hopppunktene '
                   'i deres rekkefølge.</p>\n'
                   '<p>Avhengig av rutetypen vises tilleggsinformasjon om distanse, hopp, '
                   'drivstoff eller tritium og andre tilgjengelige rutedata.</p>\n'
                   '\n'
                   '<h3>Rute og nåværende sjef</h3>\n'
                   '<p>Det nåværende systemet og skipet kan – så lenge de er klart kjent i den '
                   'aktive AppState – brukes til forhåndstildeling eller for å støtte '
                   'planlegging.</p>\n'
                   '<p>Den faktiske ruten forblir imidlertid en plan og endrer ingen journal- '
                   'eller fartøydata.</p>\n'
                   '\n'
                   '<h3>CTSVision eksport</h3>\n'
                   '<p>Beregnede flåtetransportruter kan eksporteres som CSV for CTSVision.</p>\n'
                   '<p>Dette betyr at en transportørrute planlagt i CMDRHelper så kan brukes i '
                   'CTSVision for hoppkontroll eller rutebehandling der.</p>\n'
                   '<p>Eksporten endrer ikke ruten i CMDRHelper.</p>\n'
                   '\n'
                   '<h3>CSV-fil</h3>\n'
                   '<p>Den eksporterte filen inneholder rutedataene som kreves for CTSVision i den '
                   'tiltenkte rekkefølgen.</p>\n'
                   '<p>Filen bør ikke endres strukturelt på en ukontrollert måte etter eksport '
                   'hvis den da skal leses inn av CTSVision.</p>\n'
                   '\n'
                   '<h3>Feil og eksterne tjenester</h3>\n'
                   '<p>Hvis Spansh ikke kan nås eller tjenesten returnerer en feil, viser '
                   'CMDRHelper en tilsvarende feilmelding.</p>\n'
                   '<p>En feil i online ruteberegning endrer ikke lokale fartøysjef eller '
                   'journaldata.</p>\n'
                   '\n'
                   '<h3>Ruteplanlegger og hopptips</h3>\n'
                   '<p>Hopptips og ruteplanlegger utfører forskjellige oppgaver:</p>\n'
                   '<ul>\n'
                   '<li>Jump tips evaluerer mulige interessante letemål basert på eksisterende '
                   'data.</li>\n'
                   '<li>Ruteplanlegger beregner en bestemt rute mellom start og destinasjon.</li>\n'
                   '</ul>\n'
                   '<p>Et godt hopptips er derfor ikke automatisk en del av en optimal rute.</p>\n'
                   '\n'
                   '<h3>Flere befal</h3>\n'
                   '<p>Hvis fartøysjefrelaterte data som nåværende system eller skip brukes, '
                   'kommer disse fra den aktive live AppState og må tydelig tilordnes der.</p>\n'
                   '<p>Bare å se på en annen fartøysjef i CMDR-visningen bytter ikke '
                   'ruteplanleggeren til deres system eller skip.</p>\n'
                   '<p>En ruteberegning i seg selv endrer ikke personopplysningene til en annen '
                   'fartøysjef.</p>\n'
                   '\n'
                   '<h3>Tupp</h3>\n'
                   '<p>Før en lang tur, sjekk alltid igjen:</p>\n'
                   '<ul>\n'
                   '<li>Startsystem</li>\n'
                   '<li>Målsystem</li>\n'
                   '<li>Rutetype skip/transportør</li>\n'
                   '<li>for skipsruter, det underliggende skipet, FSD og hoppparametere</li>\n'
                   '<li>for transportørruter, den tilgjengelige tritiumreserven</li>\n'
                   '</ul>\n'
                   '<p>For flåtetransportører er det tilrådelig å også planlegge tilstrekkelige '
                   'reserver for hjemreise eller uplanlagte omveier.</p>'),
 'images': ('Bilder',
            '<h2>Bilder</h2>\n'
            '<p>"Bilder"-delen administrerer skjermbildene tatt med Elite Dangerous. CMDRHelper '
            'kan automatisk gjenkjenne nye opptak, behandle dem og lagre dem i et galleri basert '
            'på kommandoen.</p>\n'
            '\n'
            '<h3>Kilde mappe</h3>\n'
            '<p>Kildemappen er mappen der Elite Dangerous lagrer skjermbilder i BMP-format.</p>\n'
            '<p>CMDRHelper kan overvåke denne mappen for nye BMP-filer. For at automatisk '
            'behandling skal fungere, må den riktige skjermbildemappen settes.</p>\n'
            '\n'
            '<h3>Destinasjonsmappe</h3>\n'
            '<p>Destinasjonsmappen er den vanlige rotmappen for bildene som behandles av '
            'CMDRHelper.</p>\n'
            '<p>Brukeren angir denne rotmappen. CMDRHelper oppretter automatisk de nødvendige '
            'sjefsrelaterte undermappene under behandlingen.</p>\n'
            '\n'
            '<h3>Automatisk behandling</h3>\n'
            '<p>Hvis "Konverter automatisk" er aktivert og gyldige kilde- og målmapper er angitt, '
            'sjekker CMDRHelper regelmessig kildemappen for nye BMP-skjermbilder.</p>\n'
            '<p>Når den er aktivert, blir eksisterende BMP-filer i utgangspunktet merket som '
            'kjente og blir ikke automatisk konvertert uten å bli spurt. Den separate funksjonen '
            'for konvertering av eksisterende BMPer er tilgjengelig for dette.</p>\n'
            '<p>En ny fil settes ikke i kø før den har samme størrelse som ikke er null i to '
            'påfølgende kontroller. Som et resultat blir ikke en skriveoperasjon som fortsatt er i '
            'gang behandlet umiddelbart.</p>\n'
            '\n'
            '<h3>Bildekonvertering</h3>\n'
            '<p>Som kilde behandler CMDRHelper BMP-filer. "PNG" eller "JPG" kan velges som '
            'målformat.</p>\n'
            '<p>JPG-filer lagres på kvalitetsnivå 95. PNG-filer lagres på en optimalisert '
            'måte.</p>\n'
            '<p>Som standard beholdes den originale BMP-filen. Hvis "Slett BMP etter konvertering" '
            'er aktivert, vil kilde-BMP bare bli slettet etter at målbildet er lagret.</p>\n'
            '\n'
            '<h3>Gjør bildet lysere</h3>\n'
            '<p>Lysstyrken justeres fra 0 til 50 prosent ved hjelp av en glidebryter og et koblet '
            'tallfelt. Innstillingen er lagret.</p>\n'
            '<p>Den brukes automatisk under hver konvertering som startes etterpå - både for nylig '
            'overvåkede og manuelt initierte eksisterende BMP-filer. 0 prosent tar over den '
            'opprinnelige lysstyrken; høyere verdier øker lysstyrken til det genererte PNG- eller '
            'JPG-bildet tilsvarende.</p>\n'
            '<p>Funksjonen er ikke en ren forhåndsvisning og brukes ikke senere på et bilde valgt '
            'i galleriet. Den endrede lysstyrken lagres i den nye målfilen.</p>\n'
            '<p>Kilde-BMP forblir uendret med mindre sletting av BMP-filen også er aktivert. '
            'Journal, fartøysjef og letedata endres ikke.</p>\n'
            '\n'
            '<h3>Kommandørrelatert lagring</h3>\n'
            '<p>Nye skjermbilder blir tilordnet den faktiske spillende Commander basert på '
            'journalidentiteten til stede i den aktive live AppState.</p>\n'
            '<p>Mappestrukturen inneholder kommandonavn og Frontier ID, for eksempel:</p>\n'
            '<p><b>FABER38_F12520967/</b></p>\n'
            '<p>FID holder oppdraget klart selv med flere sjefer. Dette gjør at to sjefer med '
            'samme navn kan skilles fra hverandre.</p>\n'
            '\n'
            '<h3>filnavn</h3>\n'
            '<p>Nye behandlede bilder får et navn med fangsttidspunkt, sjefsnavn og - hvis '
            'tilgjengelig - stjernesystemet kjent ved kø.</p>\n'
            '<p>Eksempel:</p>\n'
            '<p><b>2026-09-04_13-18-22_FABER38_Prua-Hypai-RB-D-c29-71.png</b></p>\n'
            '<p>FID er i det kommandorelaterte mappenavnet, ikke igjen i bildefilnavnet.</p>\n'
            '\n'
            '<h3>Sikre filnavn</h3>\n'
            '<p>CMDRHelper renser kommando- og systemnavn for bruk som fil- og '
            'mappekomponenter.</p>\n'
            '<p>Ulovlig kontroll og Windows-tegn erstattes, mellomrom forenes, problematiske '
            'punktum eller etterfølgende mellomrom fjernes, og reserverte Windows-navn som CON '
            'eller NUL er sikret.</p>\n'
            '\n'
            '<h3>Opptakstid</h3>\n'
            '<p>For navngivning bruker CMDRHelper modifikasjonstiden til den stabile gjenkjente '
            'BMP-filen. Kun hvis dette ikke kan leses vil gjeldende tid brukes.</p>\n'
            '<p>Dette betyr at navnet vanligvis avhenger av kildefilen og ikke av den påfølgende '
            'konverteringstiden.</p>\n'
            '\n'
            '<h3>Flere bilder i samme sekund</h3>\n'
            '<p>Hvis det tiltenkte filnavnet allerede eksisterer eller er reservert for en '
            'pågående konvertering, legger CMDRHelper det til '
            'kontinuerlig<code>_2</code>,<code>_3</code>,<code>_4</code>og så videre.</p>\n'
            '<p>Dette betyr at et annet skjermbilde med samme tidsstempel ikke vil overskrive et '
            'eksisterende målbilde.</p>\n'
            '\n'
            '<h3>Fartøyskifte under behandling</h3>\n'
            '<p>Commander, FID og systemet fanges sammen når du setter et skjermbilde i kø.</p>\n'
            '<p>Et senere skifte av befal endrer ikke tildelingen av dette allerede ventende '
            'bildet. Dette betyr at et skjermbilde av FABER38 ikke senere blir skrevet til mappen '
            'til en annen sjef.</p>\n'
            '\n'
            '<h3>galleri</h3>\n'
            '<p>Galleriet viser PNG-, JPG- og JPEG-filer fra katalogene knyttet til det valgte '
            'filteret. Nye, slettede eller flyttede bilder oppdages jevnlig.</p>\n'
            '<p>Gallerifilteret endrer ikke lagringsplasseringen eller kommandoen til filene.</p>\n'
            '\n'
            '<h3>Nåværende sjef</h3>\n'
            '<p>Current Commander-filteret viser bilder fra mappen til kommandoen som vises i '
            'CMDR-visningen.</p>\n'
            '<p>Den aktuelle fartøysjefen bestemmer kun gallerivisningen. På den annen side, '
            'tildeling av et nytt live-skjermbilde bruker journalidentiteten som er aktiv når du '
            'står i kø.</p>\n'
            '\n'
            '<h3>Alle befal</h3>\n'
            '<p>"Alle sjefer"-filteret viser bildene fra de gyldige undermappene til alle kjente '
            'sjefer sammen. Den spesielle mappen for opptak uten anerkjent identitet tas også i '
            'betraktning.</p>\n'
            '<p>Filene blir ikke flyttet eller slått sammen.</p>\n'
            '\n'
            '<h3>Ikke tildelt</h3>\n'
            '<p>Utildelt-filteret viser støttede bildefiler som ligger direkte i den delte '
            'målrotmappen.</p>\n'
            '<p>Spesielt forblir eldre bilder uten sjefsrelaterte undermapper synlige. CMDRHelper '
            'prøver ikke å gjette deres tilhørighet i etterkant.</p>\n'
            '\n'
            '<h3>Eksisterende bilder</h3>\n'
            '<p>Bilder som allerede finnes i rotmappen blir ikke automatisk flyttet eller '
            'omdøpt.</p>\n'
            '<p>De forblir tilgjengelige via «Utildelt» så lenge de er tilgjengelige som PNG, JPG '
            'eller JPEG.</p>\n'
            '\n'
            '<h3>Velg og vis bildet</h3>\n'
            '<p>Et enkelt klikk på et forhåndsvisningsbilde viser bildet skalert i '
            'forhåndsvisningsområdet og viser filnavnet.</p>\n'
            '<p>Et dobbeltklikk åpner filen med operativsystemapplikasjonen satt for bilder.</p>\n'
            '<p>Flere bilder kan merkes samtidig. Når du endrer vindusstørrelsen, skaleres '
            'forhåndsvisningen av gjeldende bilde for å passe.</p>\n'
            '\n'
            '<h3>Slett bildet</h3>\n'
            '<p>Merkede bilder kan slettes ved å bruke "Slett valgt" eller slettetasten. Før '
            'sletting vises et sikkerhetsspørsmål; Uten et utvalg påpekes først nødvendig '
            'utvalg.</p>\n'
            '<p>Bare de valgte PNG/JPG/JPEG-målfilene blir slettet fra katalogene til gjeldende '
            'gallerifilter. Den originale BMP-kildefilen påvirkes ikke.</p>\n'
            '\n'
            '<h3>Åpne målmappen</h3>\n'
            '<p>"Åpne målmappe" åpner lagringsstedet i filbehandleren og oppretter den delte '
            'rotmappen om nødvendig.</p>\n'
            '<p>"Current Commander"-filteret åpner sin eksisterende Commander-undermappe. Hvis det '
            'ennå ikke eksisterer eller et annet filter er aktivt, åpnes den delte rotmappen.</p>\n'
            '\n'
            '<h3>Sikkerhet av bildestier</h3>\n'
            '<p>Før du sletter, kontrollerer CMDRHelper den kanoniske banen til hver fil. Den må '
            'være innenfor den konfigurerte målmappen og direkte i en katalog som er tillatt av '
            'gjeldende gallerifilter.</p>\n'
            '<p>Symbolske lenker brukes ikke som kommandomapper eller galleribilder og slettes '
            'ikke via galleriet. Stier utenfor målområdet og kryssingsveier avvises.</p>\n'
            '\n'
            '<h3>Hvis ingen sjef ble oppdaget</h3>\n'
            '<p>Hvis Commander og FID mangler når et nytt opptak settes i kø, vil ikke filen bli '
            'satt på vent og vil ikke bli tildelt en kjent Commander.</p>\n'
            '<p>Det vil være i undermappen<b>UNKNOWN_UNKNOWN/</b>behandlet; filnavnet brukes også '
            'for Commander<b>UKJENT</b>. Denne mappen kan vises gjennom Alle kommandoer, ikke '
            'gjennom Uallokert rotmappefilter.</p>\n'
            '\n'
            '<h3>Flere befal</h3>\n'
            '<p>To separate regler gjelder for bildebehandling:</p>\n'
            '<ul>\n'
            '<li><b>Lagre nye bilder:</b>Den aktive journalidentiteten med Commander og FID når de '
            'står i kø, bestemmer målmappen.</li>\n'
            '<li><b>Se bilder:</b>Kommandoen som vises eller det valgte gallerifilteret bestemmer '
            'de synlige bildene.</li>\n'
            '</ul>\n'
            '<p>Dette betyr at galleriet til en annen sjef kan ses mens FABER38 spilles uten at '
            'nye skjermbilder havner i mappen til den aktuelle sjefen.</p>\n'
            '\n'
            '<h3>Tupp</h3>\n'
            '<p>En delt rotmappe for skjermbilder er tilstrekkelig. CMDRHelper separerer '
            'automatisk nylig behandlede bilder i Commander og FID.</p>\n'
            '<p>Med "Current Commander", "All Commanders" og "Unassigned" kan du bytte mellom '
            'personlig galleri, undermappene til alle kommandoer og eldre bilder i rotmappen.</p>\n'
            '<p>Høyere lysstyrke kan hjelpe med mørke bilder; det påvirker det nyopprettede '
            'målbildet under konverteringen.</p>'),
 'commander_view': ('CMDR-visning',
                    '<h2>CMDR-visning</h2>\n'
                    '<p>CMDR-visningen oppsummerer en fartøysjefs permanent lagrede personlige '
                    'opplysninger.</p>\n'
                    '<p>Den lar deg også bytte mellom de kjente sjefene for CMDRHelper og se deres '
                    'egne data. Personlig informasjon skilles ved hjelp av Frontier ID (FID).</p>\n'
                    '\n'
                    '<h3>Velg Commander</h3>\n'
                    '<p>Hvis flere sjefer er kjent, kan du bruke valget ovenfor for å finne ut '
                    'hvem som har lagret informasjon som vises. Denne sjefen er den betraktede '
                    'sjefen.</p>\n'
                    '<p>Displayet markerer det som enten "Live Active" eller "View Only".</p>\n'
                    '\n'
                    '<h3>Regnes som kommandør og livekommandør</h3>\n'
                    '<p>Å velge en annen sjef i CMDR-visningen gjør den ikke til den aktive '
                    'journalkommandøren.</p>\n'
                    '<p>Live-sjefen bestemmes utelukkende fra den for øyeblikket unikt '
                    'identifiserte Elite Dangerous-journaløkten. På denne måten kan historien til '
                    'en annen sjef ses mens Elite Dangerous fortsetter å kjøre med FABER38.</p>\n'
                    '\n'
                    '<h3>Frontier ID (FID)</h3>\n'
                    '<p>FID er den stabile Frontier-identifikatoren til en sjef.</p>\n'
                    '<p>CMDRHelper bruker den og den interne kommando-ID-en som er løst fra den '
                    'for å skille personopplysninger på en sikker måte. Kommandører med lignende '
                    'eller identiske navn forblir også adskilt.</p>\n'
                    '\n'
                    '<h3>Oversikt</h3>\n'
                    '<p>Fanen "Oversikt" viser kun permanent lagret informasjon for den aktuelle '
                    'fartøysjefen:</p>\n'
                    '<ul>\n'
                    '<li>Kommandørnavn, FID og status «Live active» eller «View only»</li>\n'
                    '<li>første og siste kjente tidspunkt</li>\n'
                    '<li>Antall besøkte systemer, bio- og geofunn, kodex-oppføringer og '
                    'kartografisalg</li>\n'
                    '<li>Siste kjente plassering og antall åpne oppdrag</li>\n'
                    '<li>nåværende eller siste skip</li>\n'
                    '<li>Fleet Carrier og operatørens plassering</li>\n'
                    '<li>Eiendeler</li>\n'
                    '<li>åpne biodata og åpne kartografiske data inkludert eksisterende '
                    'estimater</li>\n'
                    '</ul>\n'
                    '\n'
                    '<h3>Eiendeler/kreditter</h3>\n'
                    '<p>«Eiendeler»-feltet viser den sist lagrede kredittsaldoen til den aktuelle '
                    'fartøysjefen fra en passende journalhendelse, formatert som f.eks.<b>1 234 '
                    '567 kr</b>.</p>\n'
                    '<p>CMDRHelper legger ikke til fiktive inntekter eller utgifter dersom det '
                    'ikke er ny, sikker journalstatus.</p>\n'
                    '\n'
                    '<h3>Leiesoldatmynter</h3>\n'
                    '<p>Leiesoldatmyntene kommer fra MercCoins-feltene levert av Elite '
                    'Dangerous<code>Statistics → Bank_Account</code>og lagres kommandorelatert som '
                    'et Frontier øyeblikksbilde.</p>\n'
                    '<p>Synlige er:</p>\n'
                    '<ul>\n'
                    '<li>Nåværende</li>\n'
                    '<li>Totalt brukt</li>\n'
                    '<li>Engineering</li>\n'
                    '<li>utstyr</li>\n'
                    '<li>Rapportert av Frontier: tjent totalt</li>\n'
                    '</ul>\n'
                    '\n'
                    '<h3>Aktuelle og utgaver</h3>\n'
                    '<p>"Gjeldende" viser<code>MercCoins_Current</code>. «Total Spent» tar '
                    'over<code>MercCoins_Total_Spent</code>.</p>\n'
                    '<p>"Engineering" og "Equipment" viser andelene rapportert separat av '
                    'Frontier<code>MercCoins_Spent_On_Engineering</code>og<code>MercCoins_Spent_On_MercGear</code>.</p>\n'
                    '<p>For FABER38, for eksempel, en løpende beholdning av<b>1275</b>, '
                    'totalt<b>220</b>brukt og borte<b>220</b>rapportert til ingeniørarbeid.</p>\n'
                    '\n'
                    '<h3>Alt i alt fortjent</h3>\n'
                    '<p>"Rapportert av Frontier: tjent totalt" '
                    'viser<code>MercCoins_Total_Earned</code>. CMDRHelper beregner ikke egen '
                    'balanse fra dette.</p>\n'
                    '<p>Frontiers kumulative verdi trenger ikke matematisk å samsvare med '
                    'gjeldende beholdning og rapporterte utgifter. For eksempel kan 1275 '
                    'nåværende, 25 totalt opptjente og 220 totalt brukt rapporteres samtidig.</p>\n'
                    '<p>CMDRHelper korrigerer ikke disse verdiene, men viser de individuelle '
                    'Frontier-tellerne uendret.</p>\n'
                    '\n'
                    '<h3>Hvorfor ikke ha din egen MercCoins balanse?</h3>\n'
                    '<p>Elite Dangerous gir ikke en unik journalpost for hver individuelle mottak '
                    'eller utgift av leiesoldatmynter. MercCoins vises som totaler i '
                    'Statistics.</p>\n'
                    '<p>En egenberegnet bookinghistorikk vil derfor ikke være pålitelig. '
                    'CMDRHelper lagrer det siste kjente Frontier øyeblikksbildet i stedet.</p>\n'
                    '\n'
                    '<h3>Oppdrag</h3>\n'
                    '<p>"Oppdrag"-fanen viser de lagrede oppdragene til den aktuelle sjefen som en '
                    'tabell med status, oppdragsnavn, mål, utløpstid og belønning.</p>\n'
                    '\n'
                    '<h3>utforskning</h3>\n'
                    '<p>Utforskning-fanen viser åpne biodata, åpne kartografidata, biofunn, første '
                    'fotfall, selvkarterte og effektivt kartlagte kropper, og antall besøkte '
                    'systemer.</p>\n'
                    '<p>Den dedikerte "Chronicle"-fanen i CMDR-visningen er for øyeblikket '
                    'fortsatt en plassholder. Hele kronikken finner du i hovedmenypunktet med '
                    'samme navn.</p>\n'
                    '\n'
                    '<h3>Skip/flåte</h3>\n'
                    '<p>"Skips"-fanen viser først det aktive eller sist brukte skipet med '
                    'skipsnavn, skipstype, plassering og ShipID.</p>\n'
                    '<p>De lagrede skipene til den aktuelle sjefen vises under dem som utvidbare '
                    'kort. De kan sorteres stigende eller synkende etter:</p>\n'
                    '<ul>\n'
                    '<li>sist eller for øyeblikket brukt</li>\n'
                    '<li>Skipsnavn eller skipstype</li>\n'
                    '<li>maksimal hopprekkevidde</li>\n'
                    '<li>Lastekapasitet eller tom masse</li>\n'
                    '<li>sist kjente sted eller tidspunkt</li>\n'
                    '</ul>\n'
                    '<p>Du kan også filtrere for alle skip, skip med kjøretøyhangar eller skip med '
                    'jagerhangar.</p>\n'
                    '\n'
                    '<h3>Skipsdetaljer</h3>\n'
                    '<p>Et åpnet skipskart viser - hvis lagret - skips-ID, ShipID, plassering, '
                    'siste tid, maksimal hopprekkevidde, FSD og Guardian booster, masse, last og '
                    'tankkapasiteter samt utlastingstid og status.</p>\n'
                    '<p>Hvis moduldata er tilgjengelig, oppsummeres også kjøretøy- og '
                    'jagerflyhangar, skjoldgenerator og skjoldforsterker, '
                    'Guardian-skjoldforsterkninger, våpen, skrog- og modulforsterkninger og '
                    'passasjerkabiner.</p>\n'
                    '<p>Lastestatusen kan være fullstendig, ufullstendig eller foreldet. Manglende '
                    'informasjon vises som "–" og er ikke løst.</p>\n'
                    '\n'
                    '<h3>Fleet Carrier</h3>\n'
                    '<p>For en lagret tilpasset Fleet Carrier viser visningen operatørens navn, '
                    'kallesignal, operatør-ID, siste plassering og tidspunktet for siste '
                    'oppdatering.</p>\n'
                    '\n'
                    '<h3>Vedvarende sjefsstat</h3>\n'
                    '<p>Viktig fartøysjefinformasjon forblir permanent lagret. Dette gjør at '
                    'kjente verdier kan vises igjen etter en omstart av CMDRHelper eller Elite '
                    'Dangerous uten å fullstendig evaluere hver journal på nytt.</p>\n'
                    '<p>Nye unike journalhendelser oppdaterer den lagrede tilstanden.</p>\n'
                    '\n'
                    '<h3>Historisk rekonstruksjon</h3>\n'
                    '<p>For funksjoner som legges til senere, kan CMDRHelper søke i eksisterende '
                    'journalområder som tydelig er tildelt en fartøysjef én gang for informasjon '
                    'som allerede er kjent.</p>\n'
                    '<p>For eksempel kan eldre MercCoins-øyeblikksbilder tas i bruk. Gjentatte '
                    'kontroller er ikke ment å produsere dupliserte data og endrer ikke vanlige '
                    'journalleseposisjoner.</p>\n'
                    '\n'
                    '<h3>Flere befal</h3>\n'
                    '<p>Spesielt forblir følgende atskilt når det gjelder befal:</p>\n'
                    '<ul>\n'
                    '<li>Eiendeler og oppdrag</li>\n'
                    '<li>egen kartografi og organiske funn</li>\n'
                    '<li>Overflategruvehistorie og leiesoldatmynter</li>\n'
                    '<li>Online legitimasjon</li>\n'
                    '<li>sjefsrelaterte skjermbilder</li>\n'
                    '</ul>\n'
                    '<p>Globale astronomiske egenskaper til et system eller en kropp kan '
                    'imidlertid brukes sammen.</p>\n'
                    '\n'
                    '<h3>Innvirkning på andre synspunkter</h3>\n'
                    '<p>Hvis du endrer den aktuelle sjefen, oppdateres selve CMDR-visningen, det '
                    'personlige utvalget av råmateriale for gruvedrift i kronikken og, med '
                    'passende filter, skjermbildegalleriet.</p>\n'
                    '<p>Den erstatter ikke den faktiske live-kommandøren for journalbehandling '
                    'eller online opplastinger.</p>\n'
                    '\n'
                    '<h3>Inara og EDSM</h3>\n'
                    '<p>Inara- og EDSM-tilganger administreres separat per henholdsvis sjef og '
                    'FID.</p>\n'
                    '<p>Bare å se på en fartøysjef starter ikke en overføring med deres API-Key. '
                    'Bare det aktive tidsskriftet FID er relevant for live-opplastinger.</p>\n'
                    '<p>Tilgangsdataene administreres under "Innstillinger" i området for '
                    'elektroniske tjenester.</p>\n'
                    '\n'
                    '<h3>Tupp</h3>\n'
                    '<p>Bruk CMDR-visningen hvis du vil se lagret personlig informasjon for en '
                    'bestemt sjef.</p>\n'
                    '<p><b>CMDR-visning = Hvem vil jeg se?</b></p>\n'
                    '<p><b>Active Journal-FID = Hvem spiller egentlig akkurat nå?</b></p>\n'
                    '<p>Denne separasjonen forhindrer at personlige data eller online opplastinger '
                    'fra forskjellige sjefer blandes sammen.</p>'),
 'settings': ('Innstillinger',
              '<h2>Innstillinger</h2>\n'
              '<p>"Innstillinger"-området bestemmer hvordan CMDRHelper fungerer med Elite '
              'Dangerous, journalfiler, database, nettjenester, grensesnitt og oppdateringer.</p>\n'
              '<p>Endringer i legitimasjon og baner bør gjøres nøye. Kommandørrelaterte '
              'innstillinger administreres separat av Frontier ID om nødvendig.</p>\n'
              '\n'
              '<h3>tidsskrift</h3>\n'
              '<p>Journalmappen er en av de viktigste innstillingene. Den må peke til mappen der '
              'Elite Dangerous<code>Journal*.log</code>filer av Windows- eller Proton-profilen som '
              'brukes.</p>\n'
              '<p>Tidsskriftene gir blant annet:</p>\n'
              '<ul>\n'
              '<li>Fartøysjefens identitet, plassering og reise</li>\n'
              '<li>Oppdrag, skip og eiendeler</li>\n'
              '<li>Utforskning, kartografi og BIO-data</li>\n'
              '<li>Overflategruvedrift, leiesoldatmynter og andre støttede stater</li>\n'
              '</ul>\n'
              '\n'
              '<h3>Journalvisning og betjening</h3>\n'
              '<p>Journalgruppen viser mappesettet, antall journaler som er funnet, eldste og '
              'nyeste journal, navnet på den nyeste filen og tidspunktet for siste leste '
              'oppføring.</p>\n'
              '<p>"Velg journalmappe" endrer mappen. "Les nå" utløser den normale oppdateringen '
              'umiddelbart.</p>\n'
              '<p>Tydelig identifiserbare økter tildeles ved hjelp av FID. Nye komplette '
              'oppføringer behandles trinnvis; Sikre leseposisjoner forhindrer at hver journal '
              'unødvendig leses på nytt i sin helhet neste gang den startes.</p>\n'
              '\n'
              '<h3>database</h3>\n'
              '<p>CMDRHelper lagrer nødvendige data permanent i en lokal SQLite-database. Dette '
              'inkluderer globale system- og kroppsdata samt informasjon som er eksplisitt tildelt '
              'en fartøysjef.</p>\n'
              '<p>Innstillingssiden viser statistikk om de lagrede dataene. Databasen skal ikke '
              'redigeres manuelt mens CMDRHelper kjører.</p>\n'
              '\n'
              '<h3>Importer journalarkiv</h3>\n'
              '<p>"Importer journalarkiv" sammenligner fullstendig journalfilene til den angitte '
              'journalmappen med databasen. Allerede kjente journalområder tas i betraktning '
              'basert på den lagrede importinformasjonen og dupliseres ikke blindt som nye '
              'data.</p>\n'
              '<p>Under en manuelt synlig import vises fremdriften, nummeret og den nåværende '
              'behandlede filen. Etter fullføring rapporterer CMDRHelper importerte eller allerede '
              'kjente data eller en feil.</p>\n'
              '<p>Arkivimporten tjener også til å lære støttet historisk informasjon på nytt fra '
              'tydelig tilordnede tidsskrifter.</p>\n'
              '\n'
              '<h3>Kommandørrelaterte data</h3>\n'
              '<p>CMDRHelper skiller personlig informasjon basert på FID og den tilknyttede '
              'interne Commander ID. Disse inkluderer, men er ikke begrenset til, oppdrag, '
              'eiendeler, MercCoins, personlig utforskning og nettilgang.</p>\n'
              '<p>En ukjent eller tvetydig journaløkt kan ikke vilkårlig tildeles en '
              'fartøysjef.</p>\n'
              '\n'
              '<h3>Online tjenester</h3>\n'
              '<p>CMDRHelper støtter EDSM og Inara. Begge tilgangene behandles og lagres separat '
              'for hver kjent sjef eller hver FID.</p>\n'
              '<p>Valget i innstillingene avgjør bare hvem som har tilgang som for øyeblikket blir '
              'redigert eller testet. Bare sjefen som er tydelig identifisert av den aktive '
              'journaløkten, har lov til å sende live.</p>\n'
              '\n'
              '<h3>EDSM tilgang for</h3>\n'
              '<p>"EDSM tilgang for:" velger kommandoen som skal redigeres. Valget vil vise '
              '"oppsett" eller "ikke satt opp" avhengig av om en API-Key er lagret.</p>\n'
              '<p>Synlige er sjefsnavn, skjult API-Key-felt, "Bruk EDSM", en tilkoblingstest og '
              'dens siste teststatus.</p>\n'
              '<p>Hver sjef trenger sin egen passende EDSM-tilgang. Valget bytter ikke '
              'direkteopplastingsprogrammet til denne kommandoen.</p>\n'
              '\n'
              '<h3>Bruk og test EDSM</h3>\n'
              '<p>"Bruk EDSM" aktiverer eller deaktiverer tjenesten for den valgte FID. Manglende '
              'eller deaktiverte legitimasjon påvirker ikke behandling av lokal journal.</p>\n'
              '<p>"Test EDSM-tilkobling" sjekker tilgangsdataene som for øyeblikket er synlige i '
              'skjemaet. En vellykket test bekrefter forbindelsen, men endrer ikke den aktive '
              'journalen FID eller live-kommandøren.</p>\n'
              '\n'
              '<h3>Inara tilgang for</h3>\n'
              '<p>"Inara Access for:" følger det samme multi-CMDR-prinsippet. Aktivering, '
              'Inara-kommandørnavn og API-Key lagres separat for hver FID.</p>\n'
              '<p>Også her viser utvalget «oppsett» eller «ikke satt opp». En nøkkel fra en sjef '
              'brukes ikke automatisk for en annen sjef.</p>\n'
              '\n'
              '<h3>Bruk og test Inara</h3>\n'
              '<p>Med Inara satt opp og aktivert for den aktive journalen FID, kan CMDRHelper '
              'overføre støttede reise-, plasserings-, oppdrags- og skipsbegivenheter. Ikke alle '
              'journalhendelser sendes til Inara.</p>\n'
              '<p>"Test Inara-tilkobling" sjekker gjeldende synlige tilgangsdata uten å endre '
              'live-kommandøren.</p>\n'
              '\n'
              '<h3>Inara utboks</h3>\n'
              '<p>Støttede Inara-hendelser flagges konstant i en utboks før '
              'nettverksoverføring.</p>\n'
              '<p>Midlertidige feil gjør at disse oppføringene kan bevares for senere forsøk. '
              'Arbeideren behandler bare utboksen til den unikt aktive journalen FID; Påmeldinger '
              'fra andre befal er ikke inkludert.</p>\n'
              '\n'
              '<h3>Online status i overskriften</h3>\n'
              '<p>EDSM viser for øyeblikket:</p>\n'
              '<ul>\n'
              '<li><b>EDSM</b>– kan ikke brukes eller deaktiveres for den aktive FID</li>\n'
              '<li><b>EDSM venter</b>– oppsett og uten pågående overføring</li>\n'
              '<li><b>EDSM girkasse</b>– siste EDSM-behandlingskjøring ble avsluttet uten feil; '
              'Verktøytipset angir om hendelser ble sendt, journaldata ble behandlet eller ingen '
              'nye data ble funnet</li>\n'
              '<li><b>EDSM feil</b>– siste overføringsstatus er feil</li>\n'
              '</ul>\n'
              '<p>Det er for øyeblikket ingen ekstra, separat merket tilstand "EDSM aktiv" for '
              'EDSM.</p>\n'
              '<p>Inara skiller mer presist:</p>\n'
              '<ul>\n'
              '<li><b>INARA ut</b>– deaktivert for den aktive journalen FID</li>\n'
              '<li><b>INARA klar</b>– satt opp, men fortsatt uten bekreftet overføring i denne '
              'økten</li>\n'
              '<li><b>INARA overføring</b>– arbeideren sender for øyeblikket</li>\n'
              '<li><b>INARA aktiv</b>– den siste faktiske overføringen ble bekreftet</li>\n'
              '<li><b>INARA feil</b>– siste overføringsforsøk mislyktes</li>\n'
              '</ul>\n'
              '\n'
              '<h3>API-Key sikkerhet</h3>\n'
              '<p>API-Key er personlig legitimasjon. Inndatafeltene er skjult; De lagres '
              'kommandorelatert i applikasjonsinnstillingene og ikke i CMDRHelper-databasen.</p>\n'
              '<p>Nøkler skal ikke publiseres, deles i skjermbilder eller legges til offentlige '
              'depoter.</p>\n'
              '\n'
              '<h3>Bilder/skjermbilder</h3>\n'
              '<p>Kildemappe, Destinasjonsmappe, PNG/JPG, Autobehandling, BMP-sletting og '
              'Brightening fra 0 til 50 prosent er utelukkende plassert i hovedmenyen for bilder, '
              'ikke på Innstillinger-siden.</p>\n'
              '<p>Den kontekstsensitive hjelpen «Bilder» beskriver disse alternativene i '
              'detalj.</p>\n'
              '\n'
              '<h3>flate</h3>\n'
              '<p>Grensesnittgruppen inkluderer utseende, språk, font, skriftstørrelse og '
              'verditerskel for verdifulle utforskerkropper.</p>\n'
              '\n'
              '<h3>Mørk og lys modus</h3>\n'
              '<p>Du kan bytte direkte mellom mørkt og lyst utseende. Temaet brukes umiddelbart på '
              'grensesnittet og eksisterende system- og historiekort og lagres.</p>\n'
              '\n'
              '<h3>Språk</h3>\n'
              '<p>Grensesnittet tilbyr tolv språk å velge mellom. "Lagre språk" lagrer valget; En '
              'omstart av CMDRHelper er da nødvendig for en fullstendig enhetlig konvertering av '
              'eksisterende widgets.</p>\n'
              '\n'
              '<h3>Skrift og skriftstørrelse</h3>\n'
              '<p>Skriftfamilie og skriftstørrelse fra 7 til 24 pt kan velges og lagres.</p>\n'
              '<p>Begge endringene vil først tre i full effekt etter en omstart. Grensesnittet '
              'indikerer dette eksplisitt.</p>\n'
              '\n'
              '<h3>Verditerskel</h3>\n'
              '<p>Explorer-verditerskelen bestemmer den estimerte kredittverdien som organer '
              'fremheves som spesielt verdifulle. Endringen lagres umiddelbart og oppdaterer den '
              'tilsvarende Explorer-skjermen.</p>\n'
              '\n'
              '<h3>Skjul automatisk</h3>\n'
              '<p>"Precious Bodies" og "BIO Funs" er godt plassert i venstre sidefelt, ikke på '
              'Innstillinger-siden.</p>\n'
              '<p>Bryterne lagres og kontrollerer de støttede små live hintvinduene under '
              'utforskning. Verditerskelen for verdifulle kropper er satt i '
              'grensesnittinnstillingene.</p>\n'
              '\n'
              '<h3>Oppdateringer</h3>\n'
              '<p>Oppdateringsgruppen viser installert versjon og GitHub-status. Sjekk nå ser '
              'manuelt etter en ny planlagt CMDRHelper-versjon; I tillegg skjer det en forsinket '
              'automatisk kontroll etter start.</p>\n'
              '<p>Hvis en ny versjon er tilgjengelig, vil CMDRHelper spørre før du laster ned og '
              'installerer. En annonsert databaseoppdatering vises separat i denne '
              'dialogboksen.</p>\n'
              '\n'
              '<h3>Last ned fremdrift</h3>\n'
              '<p>Nedlastingen kjører i bakgrunnen. Hvis den totale størrelsen er kjent, viser '
              'CMDRHelper filnavn, mottatt og total MiB, prosent, overføringshastighet og estimert '
              'gjenværende tid.</p>\n'
              '<p>Uten en kjent totalstørrelse fungerer fremdriftslinjen i opptatt-modus og '
              'fortsetter å vise mengden data som mottas og - hvis det kan bestemmes - '
              'hastigheten. Før installasjonen sjekkes nedlastet ZIP.</p>\n'
              '\n'
              '<h3>Avbryt oppdatering</h3>\n'
              '<p>"Avbryt nedlasting" avslutter en pågående nedlasting på en kontrollert måte. En '
              'avbrutt, ufullstendig eller ugyldig nedlasting vil ikke bli installert.</p>\n'
              '\n'
              '<h3>Oppdater på Windows</h3>\n'
              '<p>På Windows fortsetter selve oppdateringsprosessen uavhengig av den opprinnelige '
              'startkonsollen. En konsollavstenging bør derfor ikke utilsiktet avslutte den.</p>\n'
              '<p>Hvis det oppstår en feil etter at filendringer har begynt, forsøker den '
              'eksisterende sikkerhetskopieringen å gjenopprette den forrige versjonen.</p>\n'
              '\n'
              '<h3>Start på nytt etter oppdatering</h3>\n'
              '<p>Etter vellykket installasjon starter oppdateringsprogrammet CMDRHelper på nytt '
              'via den tiltenkte startbanen og sjekker kort om den nye prosessen kjører '
              'stabilt.</p>\n'
              '<p>Hvis en utgivelse krever en engangsoppdatering av databasen, vil journalarkivet '
              'også bli revurdert etter omstart.</p>\n'
              '\n'
              '<h3>Flere befal</h3>\n'
              '<p><b>Valg av innstillinger = Hvem sin nettilgang redigerer jeg?</b></p>\n'
              '<p><b>Active Journal-FID = Hvem har lov til å sende direkte?</b></p>\n'
              '<p>Verken nettkontovalget eller CMDR-visningen har tillatelse til å bytte en '
              'direkteopplastingsmaskin til en visningskommandør.</p>\n'
              '\n'
              '<h3>Hjelp</h3>\n'
              '<p>"? Hjelp" er plassert i venstre sidefelt over "auto show" og åpner hjelpen til '
              'hovedmenyområdet som er synlig for øyeblikket.</p>\n'
              '<p>I "Innstillinger"-området åpner knappen denne innstillingshjelpen direkte.</p>\n'
              '\n'
              '<h3>Tupp</h3>\n'
              '<p>Hvis du installerer på nytt eller har problemer, sjekk først:</p>\n'
              '<ul>\n'
              '<li>riktig journalmappe og anerkjent befalsidentitet</li>\n'
              '<li>ønsket språk, tema, font og utforskerverditerskel</li>\n'
              '<li>Online tilgang til riktig FID</li>\n'
              '<li>I tilfelle bildeproblemer, kilde- og målmapper i hovedmenyen "Bilder".</li>\n'
              '</ul>\n'
              '<p>Hvis det er flere sjefer, vær alltid oppmerksom på hvilken FID de synlige '
              'nettilgangsdataene gjelder for.</p>')}

DIALOG_TITLE = 'Hjelp – {area}'
CLOSE_LABEL = 'Lukk'
